// =========================================================
// Vocabulary Survival - 分类词库数据集 (Words Data)
// 包含：1. 原始背诵学习词库 (468词) 2. 51章职场小说原著新词 (49词) 3. 混合总库
// =========================================================

// 1. 📖 原始背诵词库（完全还原用户原始学习与记忆背诵顺序）
const ORIGINAL_STUDY_WORDS = [
  "space",
  "universe",
  "unite",
  "reunite",
  "union",
  "diverse",
  "convert",
  "reverse",
  "anniversary",
  "annual",
  "controversy",
  "contrary",
  "contrast",
  "nasty",
  "astronaut",
  "heaven",
  "satellite",
  "moon",
  "develop",
  "evolve",
  "revolve",
  "involve",
  "advance",
  "ahead",
  "ongoing",
  "improve",
  "approve",
  "proof",
  "enhance",
  "enable",
  "enlarge",
  "enrich",
  "fasten",
  "tight",
  "buckle",
  "watertight",
  "loose",
  "undo",
  "form",
  "formal",
  "uniform",
  "formation",
  "reform",
  "format",
  "conform",
  "comply",
  "formulate",
  "formula",
  "program",
  "perform",
  "drill",
  "inform",
  "notify",
  "noticeable",
  "coast",
  "toast",
  "roast",
  "sail",
  "shore",
  "island",
  "inland",
  "beach",
  "bench",
  "harbor",
  "embrace",
  "bay",
  "shelter",
  "shade",
  "shave",
  "belt",
  "bond",
  "bind",
  "blind",
  "deaf",
  "bend",
  "twist",
  "blend",
  "mix",
  "stir",
  "mountain",
  "fountain",
  "profound",
  "foundation",
  "base",
  "basic",
  "basis",
  "mount",
  "amount",
  "soar",
  "ascend",
  "descend",
  "decline",
  "incline",
  "ancestor",
  "ancient",
  "consensus",
  "proceed",
  "procession",
  "troop",
  "process",
  "procedure",
  "access",
  "assess",
  "exceed",
  "beyond",
  "surplus",
  "extra",
  "excess",
  "success",
  "succeed",
  "successor",
  "excel",
  "stride",
  "wander",
  "crawl",
  "climb",
  "progress",
  "congress",
  "aggressive",
  "move",
  "mobile",
  "static",
  "motive",
  "motivate",
  "remove",
  "emotion",
  "rational",
  "ratio",
  "rate",
  "percentage",
  "remote",
  "promote",
  "action",
  "deed",
  "behave",
  "active",
  "react",
  "exact",
  "actual",
  "practical",
  "virtual",
  "fragment",
  "somewhat",
  "fraction",
  "portion",
  "proportion",
  "skeleton",
  "frame",
  "framework",
  "flame",
  "burn",
  "flash",
  "flesh",
  "fresh",
  "refresh",
  "flourish",
  "flour",
  "powder",
  "cure",
  "curious",
  "accurate",
  "secure",
  "rescue",
  "injure",
  "wound",
  "harm",
  "hazard",
  "danger",
  "stake",
  "risk",
  "gamble",
  "bet",
  "current",
  "currency",
  "rental",
  "lease",
  "release",
  "recently",
  "modern",
  "era",
  "up-to-date",
  "outdated",
  "stale",
  "fashion",
  "contemporary",
  "temple",
  "temporary",
  "abundant",
  "ample",
  "mass",
  "massive",
  "massage",
  "vast",
  "scope",
  "scale",
  "sculpture",
  "campaign",
  "champion",
  "chance",
  "candidate",
  "channel",
  "chapter",
  "character",
  "characteristic",
  "characterize",
  "chart",
  "chase",
  "cheat",
  "check",
  "cheek",
  "cheer",
  "cheese",
  "chef",
  "chemical",
  "chemist",
  "chemistry",
  "cherish",
  "chest",
  "child",
  "childhood",
  "chip",
  "choke",
  "choose",
  "chop",
  "cigarette",
  "cinema",
  "circle",
  "circuit",
  "circulate",
  "circumstance",
  "cite",
  "citizen",
  "city",
  "civil",
  "civilian",
  "civilization",
  "claim",
  "clap",
  "clarify",
  "clash",
  "classic",
  "classify",
  "clause",
  "clay",
  "clean",
  "clear",
  "clerk",
  "clever",
  "client",
  "cliff",
  "climate",
  "cling",
  "clinic",
  "clip",
  "clock",
  "clone",
  "cloth",
  "clothe",
  "cloud",
  "club",
  "clue",
  "clumsy",
  "coach",
  "coal",
  "coalition",
  "coarse",
  "code",
  "cognitive",
  "coincide",
  "coincidence",
  "collaborate",
  "collapse",
  "collar",
  "colleague",
  "collect",
  "collection",
  "collective",
  "college",
  "collision",
  "colonial",
  "colony",
  "color",
  "column",
  "combination",
  "combine",
  "come",
  "comedy",
  "comfort",
  "comfortable",
  "command",
  "commander",
  "comment",
  "commerce",
  "commercial",
  "commission",
  "commit",
  "commitment",
  "committee",
  "commodity",
  "common",
  "communicate",
  "communication",
  "communist",
  "community",
  "compact",
  "companion",
  "company",
  "compare",
  "comparison",
  "compete",
  "competent",
  "competition",
  "competitive",
  "competitor",
  "complain",
  "complaint",
  "complete",
  "completely",
  "complex",
  "complexity",
  "complicated",
  "component",
  "compose",
  "composition",
  "comprehensive",
  "comprise",
  "compromise",
  "compute",
  "computer",
  "concentrate",
  "concentration",
  "concept",
  "concern",
  "concerned",
  "concert",
  "conclude",
  "conclusion",
  "concrete",
  "condition",
  "conduct",
  "conference",
  "confess",
  "confidence",
  "confident",
  "confine",
  "confirm",
  "conflict",
  "confront",
  "confuse",
  "confusion",
  "connect",
  "connection",
  "conscience",
  "conscious",
  "consciousness",
  "consequence",
  "conservative",
  "consider",
  "considerable",
  "consideration",
  "consist",
  "consistent",
  "constant",
  "constantly",
  "constitute",
  "constitution",
  "construct",
  "construction",
  "consult",
  "consume",
  "consumer",
  "consumption",
  "contact",
  "contain",
  "container",
  "content",
  "contest",
  "context",
  "continent",
  "continual",
  "continue",
  "continuous",
  "contract",
  "contradiction",
  "contribute",
  "contribution",
  "control",
  "controversial",
  "convenience",
  "convenient",
  "convention",
  "conventional",
  "conversation",
  "conversion",
  "convey",
  "convince",
  "cook",
  "cool",
  "cooperate",
  "cooperation",
  "cope",
  "copy",
  "core",
  "corner",
  "corporate",
  "corporation",
  "correct",
  "correction",
  "correspond",
  "correspondent",
  "corridor",
  "corrupt",
  "corruption",
  "cost",
  "cotton",
  "couch",
  "cough",
  "could",
  "council",
  "counsel",
  "count",
  "counter",
  "country",
  "countryside",
  "county",
  "couple",
  "courage",
  "course",
  "court",
  "cousin",
  "cover",
  "coverage",
  "crack",
  "craft",
  "crash",
  "crazy",
  "cream",
  "create",
  "creation",
  "creative",
  "creature",
  "credit",
  "crew",
  "crime",
  "criminal",
  "crisis",
  "critic",
  "critical",
  "criticism",
  "criticize",
  "crop",
  "cross",
  "crowd",
  "crucial",
  "cruel",
  "crush",
  "cry",
  "crystal",
  "culture",
  "cup",
  "curiosity",
  "currently",
  "curriculum",
  "curve",
  "custom",
  "customer",
  "cut",
  "cycle"
];

// 2. 📚 职场小说原著新词（从 51 章节职场小说中提炼的高频实战词汇）
const NOVEL_EXTRACTED_WORDS = [
  "insufferable",
  "hesitate",
  "overreact",
  "interpersonal",
  "retaliate",
  "confidential",
  "extortion",
  "sabotage",
  "empathy",
  "conspire",
  "compounded",
  "incognito",
  "consolidation",
  "unprecedented",
  "acceptable",
  "persistent",
  "demoralizing",
  "colleagues",
  "cubicle",
  "boardroom",
  "inventory",
  "engagement",
  "mandatory",
  "unfortunate",
  "realization",
  "professional",
  "casual",
  "executive",
  "awkward",
  "uncomfortable",
  "specific",
  "morale",
  "promotion",
  "layoffs",
  "threshold",
  "scrutiny",
  "initiative",
  "composure",
  "maneuver",
  "defiance",
  "compromise",
  "apprehensive",
  "reluctant",
  "contingency",
  "surveillance",
  "allegation",
  "discretion",
  "leverage",
  "culprit"
];

// 3. 🌐 默认全量混合词库（原始学习词库优先，保持原始顺序）
const defaultWords = [...ORIGINAL_STUDY_WORDS, ...NOVEL_EXTRACTED_WORDS];

// 4. 🇨🇳 完整中文释义字典
const chineseDict = {
  "space": "空间; 太空",
  "universe": "宇宙; 万物",
  "unite": "联合; 团结",
  "reunite": "重聚; 重新统一",
  "union": "联盟; 工会",
  "diverse": "多样的; 不同的",
  "convert": "转变; 转换",
  "reverse": "倒退; 反转",
  "anniversary": "周年纪念日",
  "annual": "年度的; 每年的",
  "controversy": "争论; 争议",
  "contrary": "相反的",
  "contrast": "对比; 对照",
  "nasty": "恶劣的; 令人讨厌的",
  "astronaut": "宇航员",
  "heaven": "天堂; 天空",
  "satellite": "卫星; 人造卫星",
  "moon": "月亮; 月球",
  "develop": "发展; 开发",
  "evolve": "演变; 进化",
  "revolve": "旋转; 围绕",
  "involve": "包含; 牵涉",
  "advance": "前进; 提前",
  "ahead": "在前面; 领先",
  "ongoing": "进行中的; 持续的",
  "improve": "改进; 提高",
  "approve": "批准; 赞成",
  "proof": "证据; 证明",
  "enhance": "提高; 增强",
  "enable": "使能够; 开启",
  "enlarge": "扩大; 放大",
  "enrich": "使丰富; 充实",
  "fasten": "系紧; 固定",
  "tight": "紧的; 牢固的",
  "buckle": "扣紧; 屈服",
  "watertight": "严密的; 防水的",
  "loose": "宽松的; 松散的",
  "undo": "撤销; 解开",
  "form": "形式; 形成",
  "formal": "正规的; 正式的",
  "uniform": "制服; 统一的",
  "formation": "形成; 编队",
  "reform": "改革; 改造",
  "format": "格式; 版式",
  "conform": "遵从; 符合",
  "comply": "服从; 遵守",
  "formulate": "构想; 制定",
  "formula": "公式; 方案",
  "program": "程序; 计划",
  "perform": "执行; 表演",
  "drill": "训练; 钻孔",
  "inform": "通知; 告知",
  "notify": "通知; 报告",
  "noticeable": "显而易见的",
  "coast": "海岸; 沿海",
  "toast": "敬酒; 烤面包",
  "roast": "烤; 烘烤",
  "sail": "航行; 帆",
  "shore": "岸; 滨",
  "island": "岛屿; 海岛",
  "inland": "内陆的; 内地的",
  "beach": "海滩; 沙滩",
  "bench": "长凳; 工作台",
  "harbor": "港口; 庇护",
  "embrace": "拥抱; 欣然接受",
  "bay": "海湾; 港湾",
  "shelter": "避难所; 庇护",
  "shade": "阴凉; 遮蔽",
  "shave": "剃; 刮",
  "belt": "皮带; 地带",
  "bond": "纽带; 结合",
  "bind": "捆绑; 约束",
  "blind": "盲目的; 瞎的",
  "deaf": "聋的; 不愿听的",
  "bend": "弯曲; 屈服",
  "twist": "扭曲; 盘旋",
  "blend": "混合; 融合",
  "mix": "混合; 搅拌",
  "stir": "搅动; 激发",
  "mountain": "山峰; 高山",
  "fountain": "喷泉; 源泉",
  "profound": "深奥的; 深刻的",
  "foundation": "基础; 地基",
  "base": "基地; 基础",
  "basic": "基本的; 基础的",
  "basis": "基础; 根据",
  "mount": "攀登; 增加",
  "amount": "数量; 总额",
  "soar": "高飞; 暴涨",
  "ascend": "攀登; 上升",
  "descend": "下降; 遗传",
  "decline": "下降; 衰落",
  "incline": "倾斜; 倾向于",
  "ancestor": "祖先; 先辈",
  "ancient": "古代的; 古老的",
  "consensus": "共识; 一致",
  "proceed": "继续进行; 前进",
  "procession": "队伍; 行列",
  "troop": "部队; 军队",
  "process": "过程; 处理",
  "procedure": "程序; 手续",
  "access": "进入; 使用权",
  "assess": "评估; 估算",
  "exceed": "超过; 超出",
  "beyond": "超越; 在更远处",
  "surplus": "过剩; 盈余",
  "extra": "额外的; 附加的",
  "excess": "过量; 无度",
  "success": "成功; 胜利",
  "succeed": "成功; 继承",
  "successor": "继任者; 继承人",
  "excel": "胜过; 擅长",
  "stride": "大步行走; 进展",
  "wander": "漫游; 徘徊",
  "crawl": "爬行; 缓慢移动",
  "climb": "攀爬; 攀升",
  "progress": "进步; 前进",
  "congress": "国会; 代表大会",
  "aggressive": "进取的; 好斗的",
  "move": "移动; 行动",
  "mobile": "可移动的; 机动的",
  "static": "静态的; 静止的",
  "motive": "动机; 目的",
  "motivate": "激励; 促使",
  "remove": "移除; 消除",
  "emotion": "情感; 情绪",
  "rational": "理性的; 合理的",
  "ratio": "比例; 比率",
  "rate": "比率; 速度; 评价",
  "percentage": "百分比; 比例",
  "remote": "遥远的; 偏僻的",
  "promote": "促进; 提升",
  "action": "行动; 动作",
  "deed": "行为; 事迹",
  "behave": "表现; 守规矩",
  "active": "活跃的; 积极的",
  "react": "反应; 反抗",
  "exact": "精确的; 准确的",
  "actual": "实际的; 真实的",
  "practical": "实用的; 实际的",
  "virtual": "虚拟的; 实质上的",
  "fragment": "碎片; 片段",
  "somewhat": "稍微; 有点",
  "fraction": "小部分; 分数",
  "portion": "一部分; 一份",
  "proportion": "比例; 占比",
  "skeleton": "骨架; 框架",
  "frame": "框架; 骨架",
  "framework": "架构; 框架",
  "flame": "火焰; 光芒",
  "burn": "燃烧; 烧灼",
  "flash": "闪光; 闪现",
  "flesh": "肉体; 果肉",
  "fresh": "新鲜的; 清新的",
  "refresh": "使清新; 刷新",
  "flourish": "繁荣; 茂盛",
  "flour": "面粉; 粉末",
  "powder": "粉末; 细粉",
  "cure": "治愈; 治疗",
  "curious": "好奇的; 奇特的",
  "accurate": "精确的; 准确的",
  "secure": "安全的; 牢固的",
  "rescue": "营救; 救援",
  "injure": "伤害; 损害",
  "wound": "创伤; 伤口",
  "harm": "危害; 伤害",
  "hazard": "危险; 隐患",
  "danger": "危险; 危机",
  "stake": "赌注; 利害关系",
  "risk": "风险; 冒险",
  "gamble": "赌博; 投机",
  "bet": "打赌; 确信",
  "current": "当前的; 水流; 电流",
  "currency": "货币; 流通",
  "rental": "租金; 租赁",
  "lease": "租约; 租用",
  "release": "释放; 发布",
  "recently": "最近; 近期",
  "modern": "现代的; 新式的",
  "era": "时代; 纪元",
  "up-to-date": "最新的; 现代的",
  "outdated": "过时的; 陈旧的",
  "stale": "不新鲜的; 陈腐的",
  "fashion": "时尚; 方式",
  "contemporary": "当代的; 同时代的",
  "temple": "寺庙; 殿堂",
  "temporary": "暂时的; 临时的",
  "abundant": "丰富的; 充裕的",
  "ample": "充足的; 宽敞的",
  "mass": "大量; 群众",
  "massive": "巨大的; 庞大的",
  "massage": "按摩; 揉捏",
  "vast": "广阔的; 巨大的",
  "scope": "范围; 视野",
  "scale": "规模; 刻度; 比例",
  "sculpture": "雕塑; 雕刻",
  "campaign": "活动; 战役",
  "champion": "冠军; 捍卫者",
  "chance": "机会; 偶然",
  "candidate": "候选人; 应试者",
  "channel": "通道; 频道",
  "chapter": "章节; 篇章",
  "character": "性格; 角色; 汉字",
  "characteristic": "特征; 特色",
  "characterize": "以...为特征",
  "chart": "图表; 航图",
  "chase": "追赶; 追逐",
  "cheat": "欺骗; 作弊",
  "check": "检查; 支票",
  "cheek": "面颊; 脸蛋",
  "cheer": "欢呼; 振奋",
  "cheese": "奶酪; 芝士",
  "chef": "主厨; 厨师",
  "chemical": "化学的; 化学制品",
  "chemist": "化学家; 药剂师",
  "chemistry": "化学; 相互吸引",
  "cherish": "珍爱; 珍惜",
  "chest": "胸部; 箱子",
  "child": "儿童; 孩子",
  "childhood": "童年; 幼年",
  "chip": "芯片; 碎片",
  "choke": "窒息; 哽咽",
  "choose": "选择; 挑选",
  "chop": "砍; 剁碎",
  "cigarette": "香烟; 纸烟",
  "cinema": "电影院; 电影",
  "circle": "圆圈; 循环",
  "circuit": "电路; 巡回",
  "circulate": "循环; 流通",
  "circumstance": "情况; 环境",
  "cite": "引用; 引述",
  "citizen": "公民; 市民",
  "city": "城市; 都市",
  "civil": "公民的; 文明的",
  "civilian": "平民; 百姓",
  "civilization": "文明; 文化",
  "claim": "声称; 索赔",
  "clap": "鼓掌; 拍手",
  "clarify": "澄清; 阐明",
  "clash": "冲突; 碰撞",
  "classic": "经典的; 典范",
  "classify": "分类; 归类",
  "clause": "条款; 从句",
  "clay": "粘土; 泥土",
  "clean": "干净的; 清洁",
  "clear": "清晰的; 清除",
  "clerk": "店员; 职员",
  "clever": "聪明的; 机灵的",
  "client": "客户; 委托人",
  "cliff": "悬崖; 峭壁",
  "climate": "气候; 风气",
  "cling": "紧贴; 坚持",
  "clinic": "诊所; 门诊部",
  "clip": "回形针; 剪辑",
  "clock": "钟表; 时钟",
  "clone": "克隆; 复制",
  "cloth": "布料; 织物",
  "clothe": "给...穿衣",
  "cloud": "云朵; 阴云",
  "club": "俱乐部; 社团",
  "clue": "线索; 提示",
  "clumsy": "笨拙的; 笨拙",
  "coach": "教练; 长途车",
  "coal": "煤炭; 煤块",
  "coalition": "联盟; 联合政府",
  "coarse": "粗糙的; 粗俗的",
  "code": "代码; 准则",
  "cognitive": "认知的; 感知的",
  "coincide": "巧合; 一致",
  "coincidence": "巧合; 同时发生",
  "collaborate": "合作; 协作",
  "collapse": "倒塌; 崩溃",
  "collar": "衣领; 颈圈",
  "colleague": "同事; 同僚",
  "collect": "收集; 搜集",
  "collection": "收藏品; 收集",
  "collective": "集体的; 共同的",
  "college": "大学; 学院",
  "collision": "碰撞; 冲突",
  "colonial": "殖民的; 殖民地",
  "colony": "殖民地; 群体",
  "color": "颜色; 色彩",
  "column": "专栏; 圆柱",
  "combination": "结合; 组合",
  "combine": "结合; 联合",
  "come": "来到; 产生",
  "comedy": "喜剧; 搞笑",
  "comfort": "安慰; 舒适",
  "comfortable": "舒适的; 宽裕的",
  "command": "命令; 指挥",
  "commander": "指挥官; 司令官",
  "comment": "评论; 意见",
  "commerce": "商业; 贸易",
  "commercial": "商业的; 广告",
  "commission": "委员会; 委托",
  "commit": "承诺; 犯(错)",
  "commitment": "承诺; 奉献",
  "committee": "委员会",
  "commodity": "商品; 货物",
  "common": "常见的; 共同的",
  "communicate": "沟通; 传达",
  "communication": "交流; 通讯",
  "communist": "共产主义者",
  "community": "社区; 共同体",
  "compact": "紧凑的; 契约",
  "companion": "同伴; 伴侣",
  "company": "公司; 陪伴",
  "compare": "比较; 对比",
  "comparison": "比较; 对照",
  "compete": "竞争; 比赛",
  "competent": "有能力的; 胜任的",
  "competition": "比赛; 竞争",
  "competitive": "竞争激烈的; 好胜的",
  "competitor": "竞争对手; 比赛者",
  "complain": "抱怨; 投诉",
  "complaint": "抱怨; 诉苦",
  "complete": "完整的; 完成",
  "completely": "完全地; 彻底地",
  "complex": "复杂的; 综合体",
  "complexity": "复杂性; 错综",
  "complicated": "复杂的; 难懂的",
  "component": "成分; 组成部分",
  "compose": "组成; 作曲",
  "composition": "作文; 成分",
  "comprehensive": "全面的; 综合的",
  "comprise": "包含; 由...组成",
  "compromise": "妥协; 折中",
  "compute": "计算; 估算",
  "computer": "计算机; 电脑",
  "concentrate": "集中; 浓缩",
  "concentration": "专心; 专注",
  "concept": "概念; 观念",
  "concern": "关心; 涉及; 担忧",
  "concerned": "关心的; 担心的",
  "concert": "音乐会; 协同",
  "conclude": "推断; 结束",
  "conclusion": "结论; 结尾",
  "concrete": "具体的; 混凝土",
  "condition": "条件; 状态",
  "conduct": "指导; 实施; 行为",
  "conference": "会议; 研讨会",
  "confess": "坦白; 承认",
  "confidence": "信心; 信任",
  "confident": "自信的; 有信心的",
  "confine": "限制; 禁闭",
  "confirm": "确认; 证实",
  "conflict": "冲突; 争论",
  "confront": "面对; 对抗",
  "confuse": "使困惑; 混淆",
  "confusion": "困惑; 混乱",
  "connect": "连接; 关联",
  "connection": "联系; 连接",
  "conscience": "良心; 道德心",
  "conscious": "有意识的; 神志清醒的",
  "consciousness": "意识; 知觉",
  "consequence": "后果; 结果",
  "conservative": "保守的; 守旧的",
  "consider": "考虑; 认为",
  "considerable": "相当大的; 重要的",
  "consideration": "考虑; 体贴",
  "consist": "由...组成; 在于",
  "consistent": "一致的; 始终如一的",
  "constant": "持续的; 恒定的",
  "constantly": "不断地; 时常",
  "constitute": "构成; 组成",
  "constitution": "宪法; 体质",
  "construct": "建造; 构筑",
  "construction": "建设; 建筑物",
  "consult": "咨询; 请教",
  "consume": "消耗; 消费",
  "consumer": "消费者; 用户",
  "consumption": "消费; 消耗",
  "contact": "联系; 接触",
  "contain": "包含; 容纳",
  "container": "容器; 集装箱",
  "content": "内容; 满足的",
  "contest": "竞赛; 比赛",
  "context": "语境; 背景",
  "continent": "大陆; 大洲",
  "continual": "持续不断的; 频繁的",
  "continue": "继续; 延续",
  "continuous": "连续的; 持续的",
  "contract": "合同; 契约; 收缩",
  "contradiction": "矛盾; 抵触",
  "contribute": "贡献; 捐助",
  "contribution": "贡献; 捐赠",
  "control": "控制; 支配",
  "controversial": "有争议的",
  "convenience": "便利; 方便",
  "convenient": "方便的; 便利的",
  "convention": "习俗; 惯例; 大会",
  "conventional": "传统的; 常规的",
  "conversation": "对话; 谈话",
  "conversion": "转换; 转变",
  "convey": "传达; 运输",
  "convince": "说服; 使确信",
  "cook": "烹饪; 厨师",
  "cool": "凉爽的; 酷的",
  "cooperate": "合作; 配合",
  "cooperation": "合作; 协作",
  "cope": "应付; 处理",
  "copy": "复制; 副本",
  "core": "核心; 要点",
  "corner": "角落; 拐角",
  "corporate": "企业的; 法人的",
  "corporation": "公司; 集团",
  "correct": "正确的; 改正",
  "correction": "改正; 修正",
  "correspond": "符合; 相当; 通信",
  "correspondent": "通讯员; 记者",
  "corridor": "走廊; 通道",
  "corrupt": "腐败的; 堕落的",
  "corruption": "腐败; 贪污",
  "cost": "成本; 花费",
  "cotton": "棉花; 棉布",
  "couch": "沙发; 睡椅",
  "cough": "咳嗽; 咳出",
  "could": "能够; 可以",
  "council": "理事会; 委员会",
  "counsel": "咨询; 建议",
  "count": "计算; 数数; 重要",
  "counter": "柜台; 反对",
  "country": "国家; 乡村",
  "countryside": "农村; 乡下",
  "county": "县; 郡",
  "couple": "夫妇; 一对",
  "courage": "勇气; 胆量",
  "course": "课程; 过程; 路线",
  "court": "法庭; 球场",
  "cousin": "堂兄弟; 表亲",
  "cover": "覆盖; 封面; 涵盖",
  "coverage": "覆盖范围; 新闻报道",
  "crack": "破裂; 裂缝",
  "craft": "工艺; 手艺; 飞船",
  "crash": "碰撞; 坠毁; 暴跌",
  "crazy": "疯狂的; 狂热的",
  "cream": "奶油; 护肤霜",
  "create": "创造; 引起",
  "creation": "创造; 创作物",
  "creative": "有创造力的; 创新的",
  "creature": "生物; 动物",
  "credit": "信用; 赞誉; 学分",
  "crew": "全体船员; 全体机组",
  "crime": "罪行; 犯罪",
  "criminal": "罪犯; 犯法的",
  "crisis": "危机; 紧要关头",
  "critic": "批评家; 评论家",
  "critical": "关键的; 批判的",
  "criticism": "批评; 批判",
  "criticize": "批评; 指责",
  "crop": "农作物; 庄稼",
  "cross": "穿过; 十字形",
  "crowd": "人群; 拥挤",
  "crucial": "至关重要的; 决定性的",
  "cruel": "残忍的; 残酷的",
  "crush": "压碎; 镇压",
  "cry": "哭泣; 呼喊",
  "crystal": "水晶; 结晶",
  "culture": "文化; 文明",
  "cup": "杯子; 奖杯",
  "curiosity": "好奇心; 求知欲",
  "currently": "当前; 目前",
  "curriculum": "课程; 全部课程",
  "curve": "曲线; 弯曲",
  "custom": "风俗; 习惯; 海关",
  "customer": "顾客; 客户",
  "cut": "剪切; 削减",
  "cycle": "周期; 循环; 自行车",
  "insufferable": "难以忍受的; 令人厌恶的",
  "hesitate": "犹豫; 踌躇",
  "overreact": "反应过度; 感情用事",
  "interpersonal": "人际关系的; 人与人的",
  "retaliate": "报复; 回击",
  "confidential": "机密的; 秘密的",
  "extortion": "敲诈; 勒索",
  "sabotage": "蓄意破坏; 暗中颠覆",
  "empathy": "同理心; 共情",
  "conspire": "密谋; 串通",
  "compounded": "复合的; 加剧的",
  "incognito": "隐姓埋名; 伪装的",
  "consolidation": "巩固; 合并",
  "unprecedented": "史无前例的; 空前的",
  "acceptable": "可接受的; 合情合理的",
  "persistent": "执着的; 持续不退的",
  "demoralizing": "挫伤士气的; 令人沮丧的",
  "colleagues": "同事; 同僚",
  "cubicle": "小隔间; 工位",
  "boardroom": "会议室; 董事会会议室",
  "inventory": "存货; 详细清单",
  "engagement": "参与度; 订婚",
  "mandatory": "强制的; 必须的",
  "unfortunate": "不幸的; 令人遗憾的",
  "realization": "领悟; 意识到了",
  "professional": "专业的; 职业的",
  "casual": "随意的; 非正式的",
  "executive": "高管; 执行官",
  "awkward": "尴尬的; 笨拙的",
  "uncomfortable": "令人不适的; 难受的",
  "specific": "具体的; 特定的",
  "morale": "士气; 斗志",
  "promotion": "晋升; 升职",
  "layoffs": "裁员; 解雇",
  "threshold": "门槛; 临界点",
  "scrutiny": "审视; 严密审查",
  "initiative": "主动权; 倡议",
  "composure": "沉着; 镇定",
  "maneuver": "策略; 巧妙调动",
  "defiance": "挑衅; 藐视",
  "apprehensive": "忧虑的; 担心的",
  "reluctant": "不情愿的; 勉强的",
  "contingency": "应急方案; 突发事件",
  "surveillance": "监控; 监视",
  "allegation": "指控; 申诉",
  "discretion": "谨慎; 自行决定权",
  "leverage": "筹码; 杠杆作用",
  "culprit": "罪魁祸首; 始作俑者"
};

// 5. 🏷️ 词汇来源与难度分级字典
const wordTierDict = {
  "space": "cet4",
  "universe": "cet4",
  "unite": "cet4",
  "reunite": "cet4",
  "union": "cet4",
  "diverse": "cet4",
  "convert": "cet4",
  "reverse": "cet4",
  "anniversary": "cet4",
  "annual": "cet4",
  "controversy": "cet4",
  "contrary": "cet4",
  "contrast": "cet4",
  "nasty": "cet4",
  "astronaut": "cet4",
  "heaven": "cet4",
  "satellite": "cet4",
  "moon": "cet4",
  "develop": "cet4",
  "evolve": "cet4",
  "revolve": "cet4",
  "involve": "cet4",
  "advance": "cet4",
  "ahead": "cet4",
  "ongoing": "cet4",
  "improve": "cet4",
  "approve": "cet4",
  "proof": "cet4",
  "enhance": "cet4",
  "enable": "cet4",
  "enlarge": "cet4",
  "enrich": "cet4",
  "fasten": "cet4",
  "tight": "cet4",
  "buckle": "cet4",
  "watertight": "cet4",
  "loose": "cet4",
  "undo": "cet4",
  "form": "cet4",
  "formal": "cet4",
  "uniform": "cet4",
  "formation": "cet4",
  "reform": "cet4",
  "format": "cet4",
  "conform": "cet4",
  "comply": "cet4",
  "formulate": "cet4",
  "formula": "cet4",
  "program": "cet4",
  "perform": "cet4",
  "drill": "cet4",
  "inform": "cet4",
  "notify": "cet4",
  "noticeable": "cet4",
  "coast": "cet4",
  "toast": "cet4",
  "roast": "cet4",
  "sail": "cet4",
  "shore": "cet4",
  "island": "cet4",
  "inland": "cet4",
  "beach": "cet4",
  "bench": "cet4",
  "harbor": "cet4",
  "embrace": "cet4",
  "bay": "cet4",
  "shelter": "cet4",
  "shade": "cet4",
  "shave": "cet4",
  "belt": "cet4",
  "bond": "cet4",
  "bind": "cet4",
  "blind": "cet4",
  "deaf": "cet4",
  "bend": "cet4",
  "twist": "cet4",
  "blend": "cet4",
  "mix": "cet4",
  "stir": "cet4",
  "mountain": "cet4",
  "fountain": "cet4",
  "profound": "cet4",
  "foundation": "cet4",
  "base": "cet4",
  "basic": "cet4",
  "basis": "cet4",
  "mount": "cet4",
  "amount": "cet4",
  "soar": "cet4",
  "ascend": "cet4",
  "descend": "cet4",
  "decline": "cet4",
  "incline": "cet4",
  "ancestor": "cet4",
  "ancient": "cet4",
  "consensus": "cet4",
  "proceed": "cet4",
  "procession": "cet4",
  "troop": "cet4",
  "process": "cet4",
  "procedure": "cet4",
  "access": "cet4",
  "assess": "cet4",
  "exceed": "cet4",
  "beyond": "cet4",
  "surplus": "cet4",
  "extra": "cet4",
  "excess": "cet4",
  "success": "cet4",
  "succeed": "cet4",
  "successor": "cet4",
  "excel": "cet4",
  "stride": "cet4",
  "wander": "cet4",
  "crawl": "cet4",
  "climb": "cet4",
  "progress": "cet4",
  "congress": "cet4",
  "aggressive": "cet4",
  "move": "cet4",
  "mobile": "cet4",
  "static": "cet4",
  "motive": "cet4",
  "motivate": "cet4",
  "remove": "cet4",
  "emotion": "cet4",
  "rational": "cet4",
  "ratio": "cet4",
  "rate": "cet4",
  "percentage": "cet4",
  "remote": "cet4",
  "promote": "cet4",
  "action": "cet4",
  "deed": "cet4",
  "behave": "cet4",
  "active": "cet4",
  "react": "cet4",
  "exact": "cet4",
  "actual": "cet4",
  "practical": "cet4",
  "virtual": "cet4",
  "fragment": "cet4",
  "somewhat": "cet4",
  "fraction": "cet4",
  "portion": "cet4",
  "proportion": "cet4",
  "skeleton": "cet4",
  "frame": "cet4",
  "framework": "cet4",
  "flame": "cet4",
  "burn": "cet4",
  "flash": "cet4",
  "flesh": "cet4",
  "fresh": "cet4",
  "refresh": "cet4",
  "flourish": "cet4",
  "flour": "cet4",
  "powder": "cet4",
  "cure": "cet4",
  "curious": "cet4",
  "accurate": "cet4",
  "secure": "cet4",
  "rescue": "cet4",
  "injure": "cet4",
  "wound": "cet4",
  "harm": "cet4",
  "hazard": "cet4",
  "danger": "cet4",
  "stake": "cet4",
  "risk": "cet4",
  "gamble": "cet4",
  "bet": "cet4",
  "current": "cet4",
  "currency": "cet4",
  "rental": "cet4",
  "lease": "cet4",
  "release": "cet4",
  "recently": "cet4",
  "modern": "cet4",
  "era": "cet4",
  "up-to-date": "cet4",
  "outdated": "cet4",
  "stale": "cet4",
  "fashion": "cet4",
  "contemporary": "cet4",
  "temple": "cet4",
  "temporary": "cet4",
  "abundant": "cet4",
  "ample": "cet4",
  "mass": "cet4",
  "massive": "cet4",
  "massage": "cet4",
  "vast": "cet4",
  "scope": "cet4",
  "scale": "cet4",
  "sculpture": "cet4",
  "campaign": "cet4",
  "champion": "cet4",
  "chance": "cet4",
  "candidate": "cet4",
  "channel": "cet4",
  "chapter": "cet4",
  "character": "cet4",
  "characteristic": "cet4",
  "characterize": "cet4",
  "chart": "cet4",
  "chase": "cet4",
  "cheat": "cet4",
  "check": "cet4",
  "cheek": "cet4",
  "cheer": "cet4",
  "cheese": "cet4",
  "chef": "cet4",
  "chemical": "cet4",
  "chemist": "cet4",
  "chemistry": "cet4",
  "cherish": "cet4",
  "chest": "cet4",
  "child": "cet4",
  "childhood": "cet4",
  "chip": "cet4",
  "choke": "cet4",
  "choose": "cet4",
  "chop": "cet4",
  "cigarette": "cet4",
  "cinema": "cet4",
  "circle": "cet4",
  "circuit": "cet4",
  "circulate": "cet4",
  "circumstance": "cet4",
  "cite": "cet4",
  "citizen": "cet4",
  "city": "cet4",
  "civil": "cet4",
  "civilian": "cet4",
  "civilization": "cet4",
  "claim": "cet4",
  "clap": "cet4",
  "clarify": "cet4",
  "clash": "cet4",
  "classic": "cet4",
  "classify": "cet4",
  "clause": "cet4",
  "clay": "cet4",
  "clean": "cet4",
  "clear": "cet4",
  "clerk": "cet4",
  "clever": "cet4",
  "client": "cet4",
  "cliff": "cet4",
  "climate": "cet4",
  "cling": "cet4",
  "clinic": "cet4",
  "clip": "cet4",
  "clock": "cet4",
  "clone": "cet4",
  "cloth": "cet4",
  "clothe": "cet4",
  "cloud": "cet4",
  "club": "cet4",
  "clue": "cet4",
  "clumsy": "cet4",
  "coach": "cet4",
  "coal": "cet4",
  "coalition": "cet4",
  "coarse": "cet4",
  "code": "cet4",
  "cognitive": "cet4",
  "coincide": "cet4",
  "coincidence": "cet4",
  "collaborate": "cet4",
  "collapse": "cet4",
  "collar": "cet4",
  "colleague": "cet4",
  "collect": "cet4",
  "collection": "cet4",
  "collective": "cet4",
  "college": "cet4",
  "collision": "cet4",
  "colonial": "cet4",
  "colony": "cet4",
  "color": "cet4",
  "column": "cet4",
  "combination": "cet4",
  "combine": "cet4",
  "come": "cet4",
  "comedy": "cet4",
  "comfort": "cet4",
  "comfortable": "cet4",
  "command": "cet4",
  "commander": "cet4",
  "comment": "cet4",
  "commerce": "cet4",
  "commercial": "cet4",
  "commission": "cet4",
  "commit": "cet4",
  "commitment": "cet4",
  "committee": "cet4",
  "commodity": "cet4",
  "common": "cet4",
  "communicate": "cet4",
  "communication": "cet4",
  "communist": "cet4",
  "community": "cet4",
  "compact": "cet4",
  "companion": "cet4",
  "company": "cet4",
  "compare": "cet4",
  "comparison": "cet4",
  "compete": "cet4",
  "competent": "cet4",
  "competition": "cet4",
  "competitive": "cet4",
  "competitor": "cet4",
  "complain": "cet4",
  "complaint": "cet4",
  "complete": "cet4",
  "completely": "cet4",
  "complex": "cet4",
  "complexity": "cet4",
  "complicated": "cet4",
  "component": "cet4",
  "compose": "cet4",
  "composition": "cet4",
  "comprehensive": "cet4",
  "comprise": "cet4",
  "compromise": "novel",
  "compute": "cet4",
  "computer": "cet4",
  "concentrate": "cet4",
  "concentration": "cet4",
  "concept": "cet4",
  "concern": "cet4",
  "concerned": "cet4",
  "concert": "cet4",
  "conclude": "cet4",
  "conclusion": "cet4",
  "concrete": "cet4",
  "condition": "cet4",
  "conduct": "cet4",
  "conference": "cet4",
  "confess": "cet4",
  "confidence": "cet4",
  "confident": "cet4",
  "confine": "cet4",
  "confirm": "cet4",
  "conflict": "cet4",
  "confront": "cet4",
  "confuse": "cet4",
  "confusion": "cet4",
  "connect": "cet4",
  "connection": "cet4",
  "conscience": "cet4",
  "conscious": "cet4",
  "consciousness": "cet4",
  "consequence": "cet4",
  "conservative": "cet4",
  "consider": "cet4",
  "considerable": "cet4",
  "consideration": "cet4",
  "consist": "cet4",
  "consistent": "cet4",
  "constant": "cet4",
  "constantly": "cet4",
  "constitute": "cet4",
  "constitution": "cet4",
  "construct": "cet4",
  "construction": "cet4",
  "consult": "cet4",
  "consume": "cet4",
  "consumer": "cet4",
  "consumption": "cet4",
  "contact": "cet4",
  "contain": "cet4",
  "container": "cet4",
  "content": "cet4",
  "contest": "cet4",
  "context": "cet4",
  "continent": "cet4",
  "continual": "cet4",
  "continue": "cet4",
  "continuous": "cet4",
  "contract": "cet4",
  "contradiction": "cet4",
  "contribute": "cet4",
  "contribution": "cet4",
  "control": "cet4",
  "controversial": "cet4",
  "convenience": "cet4",
  "convenient": "cet4",
  "convention": "cet4",
  "conventional": "cet4",
  "conversation": "cet4",
  "conversion": "cet4",
  "convey": "cet4",
  "convince": "cet4",
  "cook": "cet4",
  "cool": "cet4",
  "cooperate": "cet4",
  "cooperation": "cet4",
  "cope": "cet4",
  "copy": "cet4",
  "core": "cet4",
  "corner": "cet4",
  "corporate": "cet4",
  "corporation": "cet4",
  "correct": "cet4",
  "correction": "cet4",
  "correspond": "cet4",
  "correspondent": "cet4",
  "corridor": "cet4",
  "corrupt": "cet4",
  "corruption": "cet4",
  "cost": "cet4",
  "cotton": "cet4",
  "couch": "cet4",
  "cough": "cet4",
  "could": "cet4",
  "council": "cet4",
  "counsel": "cet4",
  "count": "cet4",
  "counter": "cet4",
  "country": "cet4",
  "countryside": "cet4",
  "county": "cet4",
  "couple": "cet4",
  "courage": "cet4",
  "course": "cet4",
  "court": "cet4",
  "cousin": "cet4",
  "cover": "cet4",
  "coverage": "cet4",
  "crack": "cet4",
  "craft": "cet4",
  "crash": "cet4",
  "crazy": "cet4",
  "cream": "cet4",
  "create": "cet4",
  "creation": "cet4",
  "creative": "cet4",
  "creature": "cet4",
  "credit": "cet4",
  "crew": "cet4",
  "crime": "cet4",
  "criminal": "cet4",
  "crisis": "cet4",
  "critic": "cet4",
  "critical": "cet4",
  "criticism": "cet4",
  "criticize": "cet4",
  "crop": "cet4",
  "cross": "cet4",
  "crowd": "cet4",
  "crucial": "cet4",
  "cruel": "cet4",
  "crush": "cet4",
  "cry": "cet4",
  "crystal": "cet4",
  "culture": "cet4",
  "cup": "cet4",
  "curiosity": "cet4",
  "currently": "cet4",
  "curriculum": "cet4",
  "curve": "cet4",
  "custom": "cet4",
  "customer": "cet4",
  "cut": "cet4",
  "cycle": "cet4",
  "insufferable": "novel",
  "hesitate": "novel",
  "overreact": "novel",
  "interpersonal": "novel",
  "retaliate": "novel",
  "confidential": "novel",
  "extortion": "novel",
  "sabotage": "novel",
  "empathy": "novel",
  "conspire": "novel",
  "compounded": "novel",
  "incognito": "novel",
  "consolidation": "novel",
  "unprecedented": "novel",
  "acceptable": "novel",
  "persistent": "novel",
  "demoralizing": "novel",
  "colleagues": "novel",
  "cubicle": "novel",
  "boardroom": "novel",
  "inventory": "novel",
  "engagement": "novel",
  "mandatory": "novel",
  "unfortunate": "novel",
  "realization": "novel",
  "professional": "novel",
  "casual": "novel",
  "executive": "novel",
  "awkward": "novel",
  "uncomfortable": "novel",
  "specific": "novel",
  "morale": "novel",
  "promotion": "novel",
  "layoffs": "novel",
  "threshold": "novel",
  "scrutiny": "novel",
  "initiative": "novel",
  "composure": "novel",
  "maneuver": "novel",
  "defiance": "novel",
  "apprehensive": "novel",
  "reluctant": "novel",
  "contingency": "novel",
  "surveillance": "novel",
  "allegation": "novel",
  "discretion": "novel",
  "leverage": "novel",
  "culprit": "novel"
};

// 6. 词形映射与修正字典
const corrections = {};

// 全局挂载导出
if (typeof window !== 'undefined') {
  window.ORIGINAL_STUDY_WORDS = ORIGINAL_STUDY_WORDS;
  window.NOVEL_EXTRACTED_WORDS = NOVEL_EXTRACTED_WORDS;
  window.defaultWords = defaultWords;
  window.chineseDict = chineseDict;
  window.wordTierDict = wordTierDict;
  window.corrections = corrections;
}
