// ==========================================
// Vocabulary Survival - 词库与数据 (words-data.js)
// 包含 CET-4 / CET-6 / 雅思托福三阶难度标签与小说全量生词
// ==========================================

// 1. 全量 CET-4 及以上核心词汇列表 (已剔除初高中简单词)
const defaultWords = [
  "annual",
  "enlarge",
  "unite",
  "ongoing",
  "reunite",
  "watertight",
  "revolve",
  "diverse",
  "contrary",
  "evolve",
  "proof",
  "enrich",
  "buckle",
  "astronaut",
  "satellite",
  "controversy",
  "program",
  "inland",
  "uniform",
  "profound",
  "ascend",
  "blend",
  "comply",
  "island",
  "embrace",
  "decline",
  "undo",
  "descend",
  "ancestor",
  "ancient",
  "consensus",
  "fountain",
  "procession",
  "crawl",
  "assess",
  "excel",
  "congress",
  "emotion",
  "successor",
  "progress",
  "deed",
  "active",
  "framework",
  "fragment",
  "static",
  "flame",
  "access",
  "aggressive",
  "stake",
  "flash",
  "flour",
  "currency",
  "rental",
  "refresh",
  "lease",
  "recently",
  "accurate",
  "modern",
  "stale",
  "contemporary",
  "outdated",
  "abundant",
  "ample",
  "massage",
  "cheat",
  "scale",
  "cheek",
  "characteristic",
  "chop",
  "sculpture",
  "chase",
  "characterize",
  "choke",
  "cherish",
  "chemist",
  "circuit",
  "circulate",
  "cite",
  "civilization",
  "clause",
  "clip",
  "cling",
  "clone",
  "clumsy",
  "club",
  "coalition",
  "coarse",
  "clue",
  "cognitive",
  "clothe",
  "clinic",
  "coincide",
  "coincidence",
  "collaborate",
  "collective",
  "collision",
  "colonial",
  "colony",
  "commerce",
  "commander",
  "comfort",
  "command",
  "combination",
  "comedy",
  "commercial",
  "commission",
  "commit",
  "commitment",
  "committee",
  "commodity",
  "communicate",
  "communication",
  "community",
  "communist",
  "companion",
  "complexity",
  "compact",
  "competitor",
  "complex",
  "competent",
  "comprehensive",
  "concerned",
  "compromise",
  "comprise",
  "competitive",
  "concert",
  "conference",
  "confront",
  "consciousness",
  "confine",
  "conservative",
  "consideration",
  "constitute",
  "constitution",
  "consumer",
  "continual",
  "consult",
  "continent",
  "consumption",
  "continuous",
  "constantly",
  "contradiction",
  "contribution",
  "controversial",
  "convenience",
  "convention",
  "conventional",
  "convey",
  "conversion",
  "cooperation",
  "cope",
  "correspond",
  "cooperate",
  "correction",
  "correspondent",
  "corridor",
  "corporation",
  "corrupt",
  "corruption",
  "cotton",
  "cough",
  "could",
  "council",
  "counter",
  "courage",
  "county",
  "crew",
  "countryside",
  "creation",
  "coverage",
  "crisis",
  "creative",
  "counsel",
  "criticism",
  "critical",
  "crop",
  "cruel",
  "crush",
  "curiosity",
  "crystal",
  "currently",
  "curriculum",
  "customer",
  "cycle",
  "then",
  "eyes",
  "even",
  "more",
  "been",
  "there",
  "says",
  "right",
  "them",
  "would",
  "should",
  "didn",
  "myself",
  "things",
  "okay",
  "doesn",
  "were",
  "hands",
  "email",
  "looks",
  "best",
  "words",
  "shit",
  "lips",
  "years",
  "someone",
  "thought",
  "person",
  "thanks",
  "pull",
  "screen",
  "nods",
  "pulls",
  "comes",
  "turns",
  "takes",
  "friends",
  "though",
  "yeah",
  "said",
  "these",
  "makes",
  "message",
  "emails",
  "expression",
  "fingers",
  "wasn",
  "shakes",
  "feels",
  "many",
  "made",
  "grin",
  "shoulders",
  "does",
  "knew",
  "sent",
  "half",
  "real",
  "times",
  "parents",
  "probably",
  "shouldn",
  "those",
  "skin",
  "exactly",
  "seems",
  "sounds",
  "closer",
  "told",
  "smiles",
  "leans",
  "cubicle",
  "stares",
  "pretty",
  "folder",
  "drops",
  "done",
  "goes",
  "somehow",
  "quickly",
  "days",
  "weird",
  "seen",
  "gives",
  "appears",
  "minutes",
  "fake",
  "starts",
  "calls",
  "boardroom",
  "laugh",
  "arms",
  "hits",
  "terrible",
  "true",
  "shifts",
  "outside",
  "hasn",
  "walks",
  "fuck",
  "able",
  "several",
  "suddenly",
  "feet",
  "employee",
  "reply",
  "went",
  "chin",
  "herself",
  "holds",
  "bathroom",
  "continues",
  "monitor",
  "ellie",
  "haven",
  "blink",
  "himself",
  "gone",
  "knows",
  "means",
  "grabs",
  "cheeks",
  "tiny",
  "deep",
  "twists",
  "tilts",
  "aunty",
  "flashes",
  "year",
  "hours",
  "text",
  "chuckle",
  "wouldn",
  "weeks",
  "gets",
  "took",
  "aren",
  "needs",
  "couldn",
  "persian",
  "stops",
  "donut",
  "carl",
  "colleagues",
  "found",
  "meant",
  "worst",
  "relief",
  "speak",
  "came",
  "bags",
  "sort",
  "search",
  "mouse",
  "slowly",
  "spent",
  "silent",
  "attention",
  "inbox",
  "grins",
  "five",
  "keeps",
  "important",
  "employees",
  "whispers",
  "sits",
  "asks",
  "obviously",
  "lights",
  "shut",
  "tightens",
  "questions",
  "reads",
  "clicks",
  "brow",
  "thoughts",
  "tears",
  "pushes",
  "miss",
  "begins",
  "known",
  "grandma",
  "raises",
  "hoodie",
  "lets",
  "heard",
  "wants",
  "happens",
  "catches",
  "soft",
  "bullshit",
  "felt",
  "morale",
  "printer",
  "goodwin",
  "normally",
  "taken",
  "claps",
  "sometimes",
  "lately",
  "ready",
  "grid",
  "practically",
  "promotion",
  "pops",
  "temples",
  "honestly",
  "mostly",
  "lower",
  "randal",
  "breaks",
  "mutter",
  "immediately",
  "pauses",
  "returns",
  "marches",
  "presses",
  "heads",
  "draws",
  "pants",
  "christmas",
  "longer",
  "possible",
  "proud",
  "town",
  "hollow",
  "messages",
  "insides",
  "taps",
  "greg",
  "cake",
  "speaks",
  "anna",
  "joffrey",
  "fists",
  "corners",
  "papers",
  "somewhere",
  "falls",
  "warmth",
  "brows",
  "marla",
  "widen",
  "palms",
  "instantly",
  "stands",
  "smith",
  "pointedly",
  "keyboard",
  "pods",
  "fact",
  "smirk",
  "warhammer",
  "seconds",
  "twice",
  "cube",
  "blurt",
  "lives",
  "moms",
  "joey",
  "eyebrows",
  "caught",
  "given",
  "faces",
  "special",
  "throws",
  "easier",
  "mutters",
  "zebra",
  "steps",
  "booth",
  "ways",
  "harpercollins",
  "dart",
  "chairs",
  "literally",
  "headphones",
  "desks",
  "months",
  "others",
  "twitch",
  "kids",
  "huffs",
  "softens",
  "gotten",
  "weren",
  "thinks",
  "lowers",
  "threshold",
  "horrible",
  "bite",
  "laughs",
  "console",
  "carpool",
  "puts",
  "tables",
  "laughter",
  "lies",
  "sends",
  "guys",
  "places",
  "brought",
  "rolls",
  "dread",
  "rubs",
  "halts",
  "tracks",
  "plans",
  "sighs",
  "croak",
  "meetings",
  "issues",
  "teeth",
  "elevator",
  "lunchroom",
  "seriously",
  "tense",
  "escapes",
  "huff",
  "ideas",
  "boxes",
  "perfectly",
  "eyebrow",
  "favorite",
  "names",
  "written",
  "none",
  "pieces",
  "executive",
  "blinks",
  "messy",
  "tugs",
  "opens",
  "passenger",
  "bakery",
  "ashe",
  "boosters",
  "admin",
  "specific",
  "documents",
  "fridge",
  "casual",
  "layoffs",
  "slides",
  "winces",
  "reports",
  "slightly",
  "seats",
  "bottles",
  "four",
  "unfortunately",
  "leaves",
  "deeper",
  "farsi",
  "passes",
  "pounds",
  "crochet",
  "broke",
  "earlier",
  "chuckles",
  "shrugs",
  "definitely",
  "broken",
  "fifteen",
  "inventory",
  "cuts",
  "celeste",
  "donuts",
  "dogs",
  "engagement",
  "flips",
  "shows",
  "walls",
  "garbage",
  "notices",
  "pins",
  "runs",
  "usually",
  "jolt",
  "million",
  "account",
  "nails",
  "heartbeat",
  "notepad",
  "jumps",
  "aunties",
  "ticks",
  "pipes",
  "drifts",
  "nudges",
  "cards",
  "makeup",
  "instagram",
  "glasses",
  "themselves",
  "jobs",
  "quietly",
  "families",
  "grew",
  "angst",
  "legs",
  "accept",
  "forgot",
  "wrinkles",
  "clears",
  "online",
  "rushes",
  "absolutely",
  "promise",
  "mandatory",
  "habib",
  "silently",
  "cackle",
  "drinks",
  "data",
  "lifts",
  "folders",
  "knuckles",
  "locks",
  "miserable",
  "crap",
  "tells",
  "doors",
  "staples",
  "despite",
  "gestures",
  "knees",
  "bounce",
  "bones",
  "ones",
  "lungs",
  "hers",
  "fluorescent",
  "technically",
  "gave",
  "unfortunate",
  "sets",
  "discount",
  "realization",
  "ends",
  "closes",
  "glances",
  "pats",
  "roya",
  "twitches",
  "physically",
  "rings",
  "professional",
  "footsteps",
  "picks",
  "forms",
  "flinch",
  "spots",
  "points",
  "curls",
  "lingers",
  "shoes",
  "types",
  "lobby",
  "vibes",
  "crouch",
  "courses",
  "scroll",
  "letters",
  "display",
  "icon",
  "became",
  "kept",
  "awkward",
  "switch",
  "crawls",
  "dollars",
  "moves",
  "sees",
  "uncomfortable",
  "miriam",
  "ears",
  "expressions",
  "reaches",
  "vibe",
  "sharply",
  "creepy",
  "roles",
  "lane",
  "holy",
  "maroon",
  "moments",
  "texts",
  "reshteh"
];

// 2. 词汇难度分级映射表 ('cet4' | 'cet6' | 'ielts')
const wordTierDict = {
  "annual": "cet4",
  "enlarge": "cet4",
  "unite": "cet4",
  "ongoing": "cet4",
  "reunite": "cet4",
  "watertight": "cet6",
  "revolve": "cet4",
  "diverse": "cet4",
  "contrary": "cet6",
  "evolve": "cet4",
  "proof": "cet4",
  "enrich": "cet4",
  "buckle": "cet4",
  "astronaut": "cet6",
  "satellite": "cet6",
  "controversy": "ielts",
  "program": "cet4",
  "inland": "cet4",
  "uniform": "cet4",
  "profound": "ielts",
  "ascend": "cet4",
  "blend": "cet4",
  "comply": "cet4",
  "island": "cet4",
  "embrace": "cet4",
  "decline": "cet4",
  "undo": "cet4",
  "descend": "cet4",
  "ancestor": "cet6",
  "ancient": "cet4",
  "consensus": "cet6",
  "fountain": "cet6",
  "procession": "cet6",
  "crawl": "cet4",
  "assess": "cet4",
  "excel": "cet4",
  "congress": "cet6",
  "emotion": "cet6",
  "successor": "cet6",
  "progress": "cet6",
  "deed": "cet4",
  "active": "cet4",
  "framework": "cet6",
  "fragment": "cet6",
  "static": "cet4",
  "flame": "cet4",
  "access": "cet4",
  "aggressive": "cet6",
  "stake": "cet4",
  "flash": "cet4",
  "flour": "cet4",
  "currency": "cet6",
  "rental": "cet4",
  "refresh": "cet4",
  "lease": "cet4",
  "recently": "cet6",
  "accurate": "cet6",
  "modern": "cet4",
  "stale": "cet4",
  "contemporary": "ielts",
  "outdated": "cet6",
  "abundant": "cet6",
  "ample": "cet4",
  "massage": "cet4",
  "cheat": "cet4",
  "scale": "cet4",
  "cheek": "cet4",
  "characteristic": "ielts",
  "chop": "cet4",
  "sculpture": "cet6",
  "chase": "cet4",
  "characterize": "ielts",
  "choke": "cet4",
  "cherish": "cet4",
  "chemist": "cet4",
  "circuit": "cet4",
  "circulate": "cet6",
  "cite": "cet4",
  "civilization": "ielts",
  "clause": "cet4",
  "clip": "cet4",
  "cling": "cet4",
  "clone": "cet4",
  "clumsy": "cet4",
  "club": "cet4",
  "coalition": "cet6",
  "coarse": "cet4",
  "clue": "cet4",
  "cognitive": "cet6",
  "clothe": "cet4",
  "clinic": "cet4",
  "coincide": "cet6",
  "coincidence": "ielts",
  "collaborate": "ielts",
  "collective": "cet6",
  "collision": "cet6",
  "colonial": "cet6",
  "colony": "cet4",
  "commerce": "cet6",
  "commander": "cet6",
  "comfort": "cet4",
  "command": "cet4",
  "combination": "ielts",
  "comedy": "cet4",
  "commercial": "cet6",
  "commission": "cet6",
  "commit": "cet4",
  "commitment": "cet6",
  "committee": "cet6",
  "commodity": "cet6",
  "communicate": "ielts",
  "communication": "ielts",
  "community": "cet6",
  "communist": "cet6",
  "companion": "cet6",
  "complexity": "cet6",
  "compact": "cet4",
  "competitor": "cet6",
  "complex": "cet4",
  "competent": "cet6",
  "comprehensive": "ielts",
  "concerned": "cet6",
  "compromise": "cet6",
  "comprise": "cet6",
  "competitive": "ielts",
  "concert": "cet4",
  "conference": "cet6",
  "confront": "cet6",
  "consciousness": "ielts",
  "confine": "cet4",
  "conservative": "ielts",
  "consideration": "ielts",
  "constitute": "cet6",
  "constitution": "ielts",
  "consumer": "cet6",
  "continual": "cet6",
  "consult": "cet4",
  "continent": "cet6",
  "consumption": "ielts",
  "continuous": "cet6",
  "constantly": "cet6",
  "contradiction": "ielts",
  "contribution": "ielts",
  "controversial": "ielts",
  "convenience": "ielts",
  "convention": "cet6",
  "conventional": "ielts",
  "convey": "cet4",
  "conversion": "cet6",
  "cooperation": "ielts",
  "cope": "cet4",
  "correspond": "cet6",
  "cooperate": "cet6",
  "correction": "cet6",
  "correspondent": "ielts",
  "corridor": "cet6",
  "corporation": "ielts",
  "corrupt": "cet4",
  "corruption": "cet6",
  "cotton": "cet4",
  "cough": "cet4",
  "could": "cet4",
  "council": "cet4",
  "counter": "cet4",
  "courage": "cet4",
  "county": "cet4",
  "crew": "cet4",
  "countryside": "ielts",
  "creation": "cet6",
  "coverage": "cet6",
  "crisis": "cet4",
  "creative": "cet6",
  "counsel": "cet4",
  "criticism": "cet6",
  "critical": "cet6",
  "crop": "cet4",
  "cruel": "cet4",
  "crush": "cet4",
  "curiosity": "cet6",
  "crystal": "cet4",
  "currently": "cet6",
  "curriculum": "cet6",
  "customer": "cet6",
  "cycle": "cet4",
  "then": "cet4",
  "eyes": "cet4",
  "even": "cet4",
  "more": "cet4",
  "been": "cet4",
  "there": "cet4",
  "says": "cet4",
  "right": "cet4",
  "them": "cet4",
  "would": "cet4",
  "should": "cet4",
  "didn": "cet4",
  "myself": "cet4",
  "things": "cet4",
  "okay": "cet4",
  "doesn": "cet4",
  "were": "cet4",
  "hands": "cet4",
  "email": "cet4",
  "looks": "cet4",
  "best": "cet4",
  "words": "cet4",
  "shit": "cet4",
  "lips": "cet4",
  "years": "cet4",
  "someone": "cet4",
  "thought": "cet4",
  "person": "cet4",
  "thanks": "cet4",
  "pull": "cet4",
  "screen": "cet4",
  "nods": "cet4",
  "pulls": "cet4",
  "comes": "cet4",
  "turns": "cet4",
  "takes": "cet4",
  "friends": "cet4",
  "though": "cet4",
  "yeah": "cet4",
  "said": "cet4",
  "these": "cet4",
  "makes": "cet4",
  "message": "cet4",
  "emails": "cet4",
  "expression": "cet6",
  "fingers": "cet4",
  "wasn": "cet4",
  "shakes": "cet4",
  "feels": "cet4",
  "many": "cet4",
  "made": "cet4",
  "grin": "cet4",
  "shoulders": "cet6",
  "does": "cet4",
  "knew": "cet4",
  "sent": "cet4",
  "half": "cet4",
  "real": "cet4",
  "times": "cet4",
  "parents": "cet4",
  "probably": "cet6",
  "shouldn": "cet4",
  "those": "cet4",
  "skin": "cet4",
  "exactly": "cet4",
  "seems": "cet4",
  "sounds": "cet4",
  "closer": "cet4",
  "told": "cet4",
  "smiles": "cet4",
  "leans": "cet4",
  "cubicle": "cet4",
  "stares": "cet4",
  "pretty": "cet4",
  "folder": "cet4",
  "drops": "cet4",
  "done": "cet4",
  "goes": "cet4",
  "somehow": "cet4",
  "quickly": "cet4",
  "days": "cet4",
  "weird": "cet4",
  "seen": "cet4",
  "gives": "cet4",
  "appears": "cet4",
  "minutes": "cet4",
  "fake": "cet4",
  "starts": "cet4",
  "calls": "cet4",
  "boardroom": "cet6",
  "laugh": "cet4",
  "arms": "cet4",
  "hits": "cet4",
  "terrible": "cet6",
  "true": "cet4",
  "shifts": "cet4",
  "outside": "cet4",
  "hasn": "cet4",
  "walks": "cet4",
  "fuck": "cet4",
  "able": "cet6",
  "several": "cet4",
  "suddenly": "cet6",
  "feet": "cet4",
  "employee": "cet6",
  "reply": "cet4",
  "went": "cet4",
  "chin": "cet4",
  "herself": "cet4",
  "holds": "cet4",
  "bathroom": "cet6",
  "continues": "cet6",
  "monitor": "cet4",
  "ellie": "cet4",
  "haven": "cet4",
  "blink": "cet4",
  "himself": "cet4",
  "gone": "cet4",
  "knows": "cet4",
  "means": "cet4",
  "grabs": "cet4",
  "cheeks": "cet4",
  "tiny": "cet4",
  "deep": "cet4",
  "twists": "cet4",
  "tilts": "cet4",
  "aunty": "cet4",
  "flashes": "cet4",
  "year": "cet4",
  "hours": "cet4",
  "text": "cet4",
  "chuckle": "cet4",
  "wouldn": "cet4",
  "weeks": "cet4",
  "gets": "cet4",
  "took": "cet4",
  "aren": "cet4",
  "needs": "cet4",
  "couldn": "cet4",
  "persian": "cet4",
  "stops": "cet4",
  "donut": "cet4",
  "carl": "cet4",
  "colleagues": "cet6",
  "found": "cet4",
  "meant": "cet4",
  "worst": "cet4",
  "relief": "cet4",
  "speak": "cet4",
  "came": "cet4",
  "bags": "cet4",
  "sort": "cet4",
  "search": "cet4",
  "mouse": "cet4",
  "slowly": "cet4",
  "spent": "cet4",
  "silent": "cet4",
  "attention": "cet6",
  "inbox": "cet4",
  "grins": "cet4",
  "five": "cet4",
  "keeps": "cet4",
  "important": "cet6",
  "employees": "cet6",
  "whispers": "cet6",
  "sits": "cet4",
  "asks": "cet4",
  "obviously": "cet6",
  "lights": "cet4",
  "shut": "cet4",
  "tightens": "cet6",
  "questions": "cet6",
  "reads": "cet4",
  "clicks": "cet4",
  "brow": "cet4",
  "thoughts": "cet6",
  "tears": "cet4",
  "pushes": "cet4",
  "miss": "cet4",
  "begins": "cet4",
  "known": "cet4",
  "grandma": "cet4",
  "raises": "cet4",
  "hoodie": "cet4",
  "lets": "cet4",
  "heard": "cet4",
  "wants": "cet4",
  "happens": "cet4",
  "catches": "cet4",
  "soft": "cet4",
  "bullshit": "cet6",
  "felt": "cet4",
  "morale": "cet4",
  "printer": "cet4",
  "goodwin": "cet4",
  "normally": "cet6",
  "taken": "cet4",
  "claps": "cet4",
  "sometimes": "cet6",
  "lately": "cet4",
  "ready": "cet4",
  "grid": "cet4",
  "practically": "ielts",
  "promotion": "cet6",
  "pops": "cet4",
  "temples": "cet4",
  "honestly": "cet6",
  "mostly": "cet4",
  "lower": "cet4",
  "randal": "cet4",
  "breaks": "cet4",
  "mutter": "cet4",
  "immediately": "ielts",
  "pauses": "cet4",
  "returns": "cet4",
  "marches": "cet4",
  "presses": "cet4",
  "heads": "cet4",
  "draws": "cet4",
  "pants": "cet4",
  "christmas": "cet6",
  "longer": "cet4",
  "possible": "cet6",
  "proud": "cet4",
  "town": "cet4",
  "hollow": "cet4",
  "messages": "cet6",
  "insides": "cet4",
  "taps": "cet4",
  "greg": "cet4",
  "cake": "cet4",
  "speaks": "cet4",
  "anna": "cet4",
  "joffrey": "cet4",
  "fists": "cet4",
  "corners": "cet4",
  "papers": "cet4",
  "somewhere": "cet6",
  "falls": "cet4",
  "warmth": "cet4",
  "brows": "cet4",
  "marla": "cet4",
  "widen": "cet4",
  "palms": "cet4",
  "instantly": "cet6",
  "stands": "cet4",
  "smith": "cet4",
  "pointedly": "cet6",
  "keyboard": "cet6",
  "pods": "cet4",
  "fact": "cet4",
  "smirk": "cet4",
  "warhammer": "cet6",
  "seconds": "cet4",
  "twice": "cet4",
  "cube": "cet4",
  "blurt": "cet4",
  "lives": "cet4",
  "moms": "cet4",
  "joey": "cet4",
  "eyebrows": "cet6",
  "caught": "cet4",
  "given": "cet4",
  "faces": "cet4",
  "special": "cet6",
  "throws": "cet4",
  "easier": "cet4",
  "mutters": "cet4",
  "zebra": "cet4",
  "steps": "cet4",
  "booth": "cet4",
  "ways": "cet4",
  "harpercollins": "ielts",
  "dart": "cet4",
  "chairs": "cet4",
  "literally": "cet6",
  "headphones": "cet6",
  "desks": "cet4",
  "months": "cet4",
  "others": "cet4",
  "twitch": "cet4",
  "kids": "cet4",
  "huffs": "cet4",
  "softens": "cet4",
  "gotten": "cet4",
  "weren": "cet4",
  "thinks": "cet4",
  "lowers": "cet4",
  "threshold": "cet6",
  "horrible": "cet6",
  "bite": "cet4",
  "laughs": "cet4",
  "console": "cet4",
  "carpool": "cet4",
  "puts": "cet4",
  "tables": "cet4",
  "laughter": "cet6",
  "lies": "cet4",
  "sends": "cet4",
  "guys": "cet4",
  "places": "cet4",
  "brought": "cet4",
  "rolls": "cet4",
  "dread": "cet4",
  "rubs": "cet4",
  "halts": "cet4",
  "tracks": "cet4",
  "plans": "cet4",
  "sighs": "cet4",
  "croak": "cet4",
  "meetings": "cet6",
  "issues": "cet4",
  "teeth": "cet4",
  "elevator": "cet6",
  "lunchroom": "cet6",
  "seriously": "cet6",
  "tense": "cet4",
  "escapes": "cet4",
  "huff": "cet4",
  "ideas": "cet4",
  "boxes": "cet4",
  "perfectly": "cet6",
  "eyebrow": "cet4",
  "favorite": "cet6",
  "names": "cet4",
  "written": "cet4",
  "none": "cet4",
  "pieces": "cet4",
  "executive": "cet6",
  "blinks": "cet4",
  "messy": "cet4",
  "tugs": "cet4",
  "opens": "cet4",
  "passenger": "cet6",
  "bakery": "cet4",
  "ashe": "cet4",
  "boosters": "cet6",
  "admin": "cet4",
  "specific": "cet6",
  "documents": "cet6",
  "fridge": "cet4",
  "casual": "cet4",
  "layoffs": "cet4",
  "slides": "cet4",
  "winces": "cet4",
  "reports": "cet4",
  "slightly": "cet6",
  "seats": "cet4",
  "bottles": "cet4",
  "four": "cet4",
  "unfortunately": "ielts",
  "leaves": "cet4",
  "deeper": "cet4",
  "farsi": "cet4",
  "passes": "cet4",
  "pounds": "cet4",
  "crochet": "cet4",
  "broke": "cet4",
  "earlier": "cet4",
  "chuckles": "cet6",
  "shrugs": "cet4",
  "definitely": "cet6",
  "broken": "cet4",
  "fifteen": "cet4",
  "inventory": "cet6",
  "cuts": "cet4",
  "celeste": "cet4",
  "donuts": "cet4",
  "dogs": "cet4",
  "engagement": "cet6",
  "flips": "cet4",
  "shows": "cet4",
  "walls": "cet4",
  "garbage": "cet4",
  "notices": "cet4",
  "pins": "cet4",
  "runs": "cet4",
  "usually": "cet4",
  "jolt": "cet4",
  "million": "cet4",
  "account": "cet4",
  "nails": "cet4",
  "heartbeat": "cet6",
  "notepad": "cet4",
  "jumps": "cet4",
  "aunties": "cet4",
  "ticks": "cet4",
  "pipes": "cet4",
  "drifts": "cet4",
  "nudges": "cet4",
  "cards": "cet4",
  "makeup": "cet4",
  "instagram": "cet6",
  "glasses": "cet4",
  "themselves": "cet6",
  "jobs": "cet4",
  "quietly": "cet4",
  "families": "cet6",
  "grew": "cet4",
  "angst": "cet4",
  "legs": "cet4",
  "accept": "cet4",
  "forgot": "cet4",
  "wrinkles": "cet6",
  "clears": "cet4",
  "online": "cet4",
  "rushes": "cet4",
  "absolutely": "cet6",
  "promise": "cet4",
  "mandatory": "cet6",
  "habib": "cet4",
  "silently": "cet6",
  "cackle": "cet4",
  "drinks": "cet4",
  "data": "cet4",
  "lifts": "cet4",
  "folders": "cet4",
  "knuckles": "cet6",
  "locks": "cet4",
  "miserable": "cet6",
  "crap": "cet4",
  "tells": "cet4",
  "doors": "cet4",
  "staples": "cet4",
  "despite": "cet4",
  "gestures": "cet6",
  "knees": "cet4",
  "bounce": "cet4",
  "bones": "cet4",
  "ones": "cet4",
  "lungs": "cet4",
  "hers": "cet4",
  "fluorescent": "ielts",
  "technically": "ielts",
  "gave": "cet4",
  "unfortunate": "ielts",
  "sets": "cet4",
  "discount": "cet6",
  "realization": "ielts",
  "ends": "cet4",
  "closes": "cet4",
  "glances": "cet4",
  "pats": "cet4",
  "roya": "cet4",
  "twitches": "cet6",
  "physically": "cet6",
  "rings": "cet4",
  "professional": "ielts",
  "footsteps": "cet6",
  "picks": "cet4",
  "forms": "cet4",
  "flinch": "cet4",
  "spots": "cet4",
  "points": "cet4",
  "curls": "cet4",
  "lingers": "cet4",
  "shoes": "cet4",
  "types": "cet4",
  "lobby": "cet4",
  "vibes": "cet4",
  "crouch": "cet4",
  "courses": "cet4",
  "scroll": "cet4",
  "letters": "cet4",
  "display": "cet4",
  "icon": "cet4",
  "became": "cet4",
  "kept": "cet4",
  "awkward": "cet4",
  "switch": "cet4",
  "crawls": "cet4",
  "dollars": "cet4",
  "moves": "cet4",
  "sees": "cet4",
  "uncomfortable": "ielts",
  "miriam": "cet4",
  "ears": "cet4",
  "expressions": "ielts",
  "reaches": "cet4",
  "vibe": "cet4",
  "sharply": "cet4",
  "creepy": "cet4",
  "roles": "cet4",
  "lane": "cet4",
  "holy": "cet4",
  "maroon": "cet4",
  "moments": "cet4",
  "texts": "cet4",
  "reshteh": "cet4"
};

// 3. 词汇中简释义表 (用于消消乐与卡片速览)
const chineseDict = {
  "annual": "annual",
  "enlarge": "enlarge",
  "unite": "unite",
  "ongoing": "ongoing",
  "reunite": "reunite",
  "watertight": "watertight",
  "revolve": "revolve",
  "diverse": "diverse",
  "contrary": "contrary",
  "evolve": "evolve",
  "proof": "proof",
  "enrich": "enrich",
  "buckle": "buckle",
  "astronaut": "astronaut",
  "satellite": "satellite",
  "controversy": "controversy",
  "program": "program",
  "inland": "inland",
  "uniform": "uniform",
  "profound": "profound",
  "ascend": "ascend",
  "blend": "blend",
  "comply": "comply",
  "island": "island",
  "embrace": "embrace",
  "decline": "decline",
  "undo": "undo",
  "descend": "descend",
  "ancestor": "ancestor",
  "ancient": "ancient",
  "consensus": "consensus",
  "fountain": "fountain",
  "procession": "procession",
  "crawl": "crawl",
  "assess": "assess",
  "excel": "excel",
  "congress": "congress",
  "emotion": "emotion",
  "successor": "successor",
  "progress": "progress",
  "deed": "deed",
  "active": "active",
  "framework": "framework",
  "fragment": "fragment",
  "static": "static",
  "flame": "flame",
  "access": "access",
  "aggressive": "aggressive",
  "stake": "stake",
  "flash": "flash",
  "flour": "flour",
  "currency": "currency",
  "rental": "rental",
  "refresh": "refresh",
  "lease": "lease",
  "recently": "recently",
  "accurate": "accurate",
  "modern": "modern",
  "stale": "stale",
  "contemporary": "contemporary",
  "outdated": "outdated",
  "abundant": "abundant",
  "ample": "ample",
  "massage": "massage",
  "cheat": "cheat",
  "scale": "scale",
  "cheek": "cheek",
  "characteristic": "characteristic",
  "chop": "chop",
  "sculpture": "sculpture",
  "chase": "chase",
  "characterize": "characterize",
  "choke": "choke",
  "cherish": "cherish",
  "chemist": "chemist",
  "circuit": "circuit",
  "circulate": "circulate",
  "cite": "cite",
  "civilization": "civilization",
  "clause": "clause",
  "clip": "clip",
  "cling": "cling",
  "clone": "clone",
  "clumsy": "clumsy",
  "club": "club",
  "coalition": "coalition",
  "coarse": "coarse",
  "clue": "clue",
  "cognitive": "cognitive",
  "clothe": "clothe",
  "clinic": "clinic",
  "coincide": "coincide",
  "coincidence": "coincidence",
  "collaborate": "collaborate",
  "collective": "collective",
  "collision": "collision",
  "colonial": "colonial",
  "colony": "colony",
  "commerce": "commerce",
  "commander": "commander",
  "comfort": "comfort",
  "command": "command",
  "combination": "combination",
  "comedy": "comedy",
  "commercial": "commercial",
  "commission": "commission",
  "commit": "commit",
  "commitment": "commitment",
  "committee": "committee",
  "commodity": "commodity",
  "communicate": "communicate",
  "communication": "communication",
  "community": "community",
  "communist": "communist",
  "companion": "companion",
  "complexity": "complexity",
  "compact": "compact",
  "competitor": "competitor",
  "complex": "complex",
  "competent": "competent",
  "comprehensive": "comprehensive",
  "concerned": "concerned",
  "compromise": "compromise",
  "comprise": "comprise",
  "competitive": "competitive",
  "concert": "concert",
  "conference": "conference",
  "confront": "confront",
  "consciousness": "consciousness",
  "confine": "confine",
  "conservative": "conservative",
  "consideration": "consideration",
  "constitute": "constitute",
  "constitution": "constitution",
  "consumer": "consumer",
  "continual": "continual",
  "consult": "consult",
  "continent": "continent",
  "consumption": "consumption",
  "continuous": "continuous",
  "constantly": "constantly",
  "contradiction": "contradiction",
  "contribution": "contribution",
  "controversial": "controversial",
  "convenience": "convenience",
  "convention": "convention",
  "conventional": "conventional",
  "convey": "convey",
  "conversion": "conversion",
  "cooperation": "cooperation",
  "cope": "cope",
  "correspond": "correspond",
  "cooperate": "cooperate",
  "correction": "correction",
  "correspondent": "correspondent",
  "corridor": "corridor",
  "corporation": "corporation",
  "corrupt": "corrupt",
  "corruption": "corruption",
  "cotton": "cotton",
  "cough": "cough",
  "could": "could",
  "council": "council",
  "counter": "counter",
  "courage": "courage",
  "county": "county",
  "crew": "crew",
  "countryside": "countryside",
  "creation": "creation",
  "coverage": "coverage",
  "crisis": "crisis",
  "creative": "creative",
  "counsel": "counsel",
  "criticism": "criticism",
  "critical": "critical",
  "crop": "crop",
  "cruel": "cruel",
  "crush": "crush",
  "curiosity": "curiosity",
  "crystal": "crystal",
  "currently": "currently",
  "curriculum": "curriculum",
  "customer": "customer",
  "cycle": "cycle",
  "then": "then",
  "eyes": "eyes",
  "even": "even",
  "more": "more",
  "been": "been",
  "there": "there",
  "says": "says",
  "right": "right",
  "them": "them",
  "would": "would",
  "should": "should",
  "didn": "didn",
  "myself": "myself",
  "things": "things",
  "okay": "okay",
  "doesn": "doesn",
  "were": "were",
  "hands": "hands",
  "email": "email",
  "looks": "looks",
  "best": "best",
  "words": "words",
  "shit": "shit",
  "lips": "lips",
  "years": "years",
  "someone": "someone",
  "thought": "thought",
  "person": "person",
  "thanks": "thanks",
  "pull": "pull",
  "screen": "screen",
  "nods": "nods",
  "pulls": "pulls",
  "comes": "comes",
  "turns": "turns",
  "takes": "takes",
  "friends": "friends",
  "though": "though",
  "yeah": "yeah",
  "said": "said",
  "these": "these",
  "makes": "makes",
  "message": "message",
  "emails": "emails",
  "expression": "expression",
  "fingers": "fingers",
  "wasn": "wasn",
  "shakes": "shakes",
  "feels": "feels",
  "many": "many",
  "made": "made",
  "grin": "grin",
  "shoulders": "shoulders",
  "does": "does",
  "knew": "knew",
  "sent": "sent",
  "half": "half",
  "real": "real",
  "times": "times",
  "parents": "parents",
  "probably": "probably",
  "shouldn": "shouldn",
  "those": "those",
  "skin": "skin",
  "exactly": "exactly",
  "seems": "seems",
  "sounds": "sounds",
  "closer": "closer",
  "told": "told",
  "smiles": "smiles",
  "leans": "leans",
  "cubicle": "cubicle",
  "stares": "stares",
  "pretty": "pretty",
  "folder": "folder",
  "drops": "drops",
  "done": "done",
  "goes": "goes",
  "somehow": "somehow",
  "quickly": "quickly",
  "days": "days",
  "weird": "weird",
  "seen": "seen",
  "gives": "gives",
  "appears": "appears",
  "minutes": "minutes",
  "fake": "fake",
  "starts": "starts",
  "calls": "calls",
  "boardroom": "boardroom",
  "laugh": "laugh",
  "arms": "arms",
  "hits": "hits",
  "terrible": "terrible",
  "true": "true",
  "shifts": "shifts",
  "outside": "outside",
  "hasn": "hasn",
  "walks": "walks",
  "fuck": "fuck",
  "able": "able",
  "several": "several",
  "suddenly": "suddenly",
  "feet": "feet",
  "employee": "employee",
  "reply": "reply",
  "went": "went",
  "chin": "chin",
  "herself": "herself",
  "holds": "holds",
  "bathroom": "bathroom",
  "continues": "continues",
  "monitor": "monitor",
  "ellie": "ellie",
  "haven": "haven",
  "blink": "blink",
  "himself": "himself",
  "gone": "gone",
  "knows": "knows",
  "means": "means",
  "grabs": "grabs",
  "cheeks": "cheeks",
  "tiny": "tiny",
  "deep": "deep",
  "twists": "twists",
  "tilts": "tilts",
  "aunty": "aunty",
  "flashes": "flashes",
  "year": "year",
  "hours": "hours",
  "text": "text",
  "chuckle": "chuckle",
  "wouldn": "wouldn",
  "weeks": "weeks",
  "gets": "gets",
  "took": "took",
  "aren": "aren",
  "needs": "needs",
  "couldn": "couldn",
  "persian": "persian",
  "stops": "stops",
  "donut": "donut",
  "carl": "carl",
  "colleagues": "colleagues",
  "found": "found",
  "meant": "meant",
  "worst": "worst",
  "relief": "relief",
  "speak": "speak",
  "came": "came",
  "bags": "bags",
  "sort": "sort",
  "search": "search",
  "mouse": "mouse",
  "slowly": "slowly",
  "spent": "spent",
  "silent": "silent",
  "attention": "attention",
  "inbox": "inbox",
  "grins": "grins",
  "five": "five",
  "keeps": "keeps",
  "important": "important",
  "employees": "employees",
  "whispers": "whispers",
  "sits": "sits",
  "asks": "asks",
  "obviously": "obviously",
  "lights": "lights",
  "shut": "shut",
  "tightens": "tightens",
  "questions": "questions",
  "reads": "reads",
  "clicks": "clicks",
  "brow": "brow",
  "thoughts": "thoughts",
  "tears": "tears",
  "pushes": "pushes",
  "miss": "miss",
  "begins": "begins",
  "known": "known",
  "grandma": "grandma",
  "raises": "raises",
  "hoodie": "hoodie",
  "lets": "lets",
  "heard": "heard",
  "wants": "wants",
  "happens": "happens",
  "catches": "catches",
  "soft": "soft",
  "bullshit": "bullshit",
  "felt": "felt",
  "morale": "morale",
  "printer": "printer",
  "goodwin": "goodwin",
  "normally": "normally",
  "taken": "taken",
  "claps": "claps",
  "sometimes": "sometimes",
  "lately": "lately",
  "ready": "ready",
  "grid": "grid",
  "practically": "practically",
  "promotion": "promotion",
  "pops": "pops",
  "temples": "temples",
  "honestly": "honestly",
  "mostly": "mostly",
  "lower": "lower",
  "randal": "randal",
  "breaks": "breaks",
  "mutter": "mutter",
  "immediately": "immediately",
  "pauses": "pauses",
  "returns": "returns",
  "marches": "marches",
  "presses": "presses",
  "heads": "heads",
  "draws": "draws",
  "pants": "pants",
  "christmas": "christmas",
  "longer": "longer",
  "possible": "possible",
  "proud": "proud",
  "town": "town",
  "hollow": "hollow",
  "messages": "messages",
  "insides": "insides",
  "taps": "taps",
  "greg": "greg",
  "cake": "cake",
  "speaks": "speaks",
  "anna": "anna",
  "joffrey": "joffrey",
  "fists": "fists",
  "corners": "corners",
  "papers": "papers",
  "somewhere": "somewhere",
  "falls": "falls",
  "warmth": "warmth",
  "brows": "brows",
  "marla": "marla",
  "widen": "widen",
  "palms": "palms",
  "instantly": "instantly",
  "stands": "stands",
  "smith": "smith",
  "pointedly": "pointedly",
  "keyboard": "keyboard",
  "pods": "pods",
  "fact": "fact",
  "smirk": "smirk",
  "warhammer": "warhammer",
  "seconds": "seconds",
  "twice": "twice",
  "cube": "cube",
  "blurt": "blurt",
  "lives": "lives",
  "moms": "moms",
  "joey": "joey",
  "eyebrows": "eyebrows",
  "caught": "caught",
  "given": "given",
  "faces": "faces",
  "special": "special",
  "throws": "throws",
  "easier": "easier",
  "mutters": "mutters",
  "zebra": "zebra",
  "steps": "steps",
  "booth": "booth",
  "ways": "ways",
  "harpercollins": "harpercollins",
  "dart": "dart",
  "chairs": "chairs",
  "literally": "literally",
  "headphones": "headphones",
  "desks": "desks",
  "months": "months",
  "others": "others",
  "twitch": "twitch",
  "kids": "kids",
  "huffs": "huffs",
  "softens": "softens",
  "gotten": "gotten",
  "weren": "weren",
  "thinks": "thinks",
  "lowers": "lowers",
  "threshold": "threshold",
  "horrible": "horrible",
  "bite": "bite",
  "laughs": "laughs",
  "console": "console",
  "carpool": "carpool",
  "puts": "puts",
  "tables": "tables",
  "laughter": "laughter",
  "lies": "lies",
  "sends": "sends",
  "guys": "guys",
  "places": "places",
  "brought": "brought",
  "rolls": "rolls",
  "dread": "dread",
  "rubs": "rubs",
  "halts": "halts",
  "tracks": "tracks",
  "plans": "plans",
  "sighs": "sighs",
  "croak": "croak",
  "meetings": "meetings",
  "issues": "issues",
  "teeth": "teeth",
  "elevator": "elevator",
  "lunchroom": "lunchroom",
  "seriously": "seriously",
  "tense": "tense",
  "escapes": "escapes",
  "huff": "huff",
  "ideas": "ideas",
  "boxes": "boxes",
  "perfectly": "perfectly",
  "eyebrow": "eyebrow",
  "favorite": "favorite",
  "names": "names",
  "written": "written",
  "none": "none",
  "pieces": "pieces",
  "executive": "executive",
  "blinks": "blinks",
  "messy": "messy",
  "tugs": "tugs",
  "opens": "opens",
  "passenger": "passenger",
  "bakery": "bakery",
  "ashe": "ashe",
  "boosters": "boosters",
  "admin": "admin",
  "specific": "specific",
  "documents": "documents",
  "fridge": "fridge",
  "casual": "casual",
  "layoffs": "layoffs",
  "slides": "slides",
  "winces": "winces",
  "reports": "reports",
  "slightly": "slightly",
  "seats": "seats",
  "bottles": "bottles",
  "four": "four",
  "unfortunately": "unfortunately",
  "leaves": "leaves",
  "deeper": "deeper",
  "farsi": "farsi",
  "passes": "passes",
  "pounds": "pounds",
  "crochet": "crochet",
  "broke": "broke",
  "earlier": "earlier",
  "chuckles": "chuckles",
  "shrugs": "shrugs",
  "definitely": "definitely",
  "broken": "broken",
  "fifteen": "fifteen",
  "inventory": "inventory",
  "cuts": "cuts",
  "celeste": "celeste",
  "donuts": "donuts",
  "dogs": "dogs",
  "engagement": "engagement",
  "flips": "flips",
  "shows": "shows",
  "walls": "walls",
  "garbage": "garbage",
  "notices": "notices",
  "pins": "pins",
  "runs": "runs",
  "usually": "usually",
  "jolt": "jolt",
  "million": "million",
  "account": "account",
  "nails": "nails",
  "heartbeat": "heartbeat",
  "notepad": "notepad",
  "jumps": "jumps",
  "aunties": "aunties",
  "ticks": "ticks",
  "pipes": "pipes",
  "drifts": "drifts",
  "nudges": "nudges",
  "cards": "cards",
  "makeup": "makeup",
  "instagram": "instagram",
  "glasses": "glasses",
  "themselves": "themselves",
  "jobs": "jobs",
  "quietly": "quietly",
  "families": "families",
  "grew": "grew",
  "angst": "angst",
  "legs": "legs",
  "accept": "accept",
  "forgot": "forgot",
  "wrinkles": "wrinkles",
  "clears": "clears",
  "online": "online",
  "rushes": "rushes",
  "absolutely": "absolutely",
  "promise": "promise",
  "mandatory": "mandatory",
  "habib": "habib",
  "silently": "silently",
  "cackle": "cackle",
  "drinks": "drinks",
  "data": "data",
  "lifts": "lifts",
  "folders": "folders",
  "knuckles": "knuckles",
  "locks": "locks",
  "miserable": "miserable",
  "crap": "crap",
  "tells": "tells",
  "doors": "doors",
  "staples": "staples",
  "despite": "despite",
  "gestures": "gestures",
  "knees": "knees",
  "bounce": "bounce",
  "bones": "bones",
  "ones": "ones",
  "lungs": "lungs",
  "hers": "hers",
  "fluorescent": "fluorescent",
  "technically": "technically",
  "gave": "gave",
  "unfortunate": "unfortunate",
  "sets": "sets",
  "discount": "discount",
  "realization": "realization",
  "ends": "ends",
  "closes": "closes",
  "glances": "glances",
  "pats": "pats",
  "roya": "roya",
  "twitches": "twitches",
  "physically": "physically",
  "rings": "rings",
  "professional": "professional",
  "footsteps": "footsteps",
  "picks": "picks",
  "forms": "forms",
  "flinch": "flinch",
  "spots": "spots",
  "points": "points",
  "curls": "curls",
  "lingers": "lingers",
  "shoes": "shoes",
  "types": "types",
  "lobby": "lobby",
  "vibes": "vibes",
  "crouch": "crouch",
  "courses": "courses",
  "scroll": "scroll",
  "letters": "letters",
  "display": "display",
  "icon": "icon",
  "became": "became",
  "kept": "kept",
  "awkward": "awkward",
  "switch": "switch",
  "crawls": "crawls",
  "dollars": "dollars",
  "moves": "moves",
  "sees": "sees",
  "uncomfortable": "uncomfortable",
  "miriam": "miriam",
  "ears": "ears",
  "expressions": "expressions",
  "reaches": "reaches",
  "vibe": "vibe",
  "sharply": "sharply",
  "creepy": "creepy",
  "roles": "roles",
  "lane": "lane",
  "holy": "holy",
  "maroon": "maroon",
  "moments": "moments",
  "texts": "texts",
  "reshteh": "reshteh"
};

// 4. 词汇完整词性与多义项释义表 (用于词典查词详情)
const fullChineseDict = {
  "annual": "annual",
  "enlarge": "enlarge",
  "unite": "unite",
  "ongoing": "ongoing",
  "reunite": "reunite",
  "watertight": "watertight",
  "revolve": "revolve",
  "diverse": "diverse",
  "contrary": "contrary",
  "evolve": "evolve",
  "proof": "proof",
  "enrich": "enrich",
  "buckle": "buckle",
  "astronaut": "astronaut",
  "satellite": "satellite",
  "controversy": "controversy",
  "program": "program",
  "inland": "inland",
  "uniform": "uniform",
  "profound": "profound",
  "ascend": "ascend",
  "blend": "blend",
  "comply": "comply",
  "island": "island",
  "embrace": "embrace",
  "decline": "decline",
  "undo": "undo",
  "descend": "descend",
  "ancestor": "ancestor",
  "ancient": "ancient",
  "consensus": "consensus",
  "fountain": "fountain",
  "procession": "procession",
  "crawl": "crawl",
  "assess": "assess",
  "excel": "excel",
  "congress": "congress",
  "emotion": "emotion",
  "successor": "successor",
  "progress": "progress",
  "deed": "deed",
  "active": "active",
  "framework": "framework",
  "fragment": "fragment",
  "static": "static",
  "flame": "flame",
  "access": "access",
  "aggressive": "aggressive",
  "stake": "stake",
  "flash": "flash",
  "flour": "flour",
  "currency": "currency",
  "rental": "rental",
  "refresh": "refresh",
  "lease": "lease",
  "recently": "recently",
  "accurate": "accurate",
  "modern": "modern",
  "stale": "stale",
  "contemporary": "contemporary",
  "outdated": "outdated",
  "abundant": "abundant",
  "ample": "ample",
  "massage": "massage",
  "cheat": "cheat",
  "scale": "scale",
  "cheek": "cheek",
  "characteristic": "characteristic",
  "chop": "chop",
  "sculpture": "sculpture",
  "chase": "chase",
  "characterize": "characterize",
  "choke": "choke",
  "cherish": "cherish",
  "chemist": "chemist",
  "circuit": "circuit",
  "circulate": "circulate",
  "cite": "cite",
  "civilization": "civilization",
  "clause": "clause",
  "clip": "clip",
  "cling": "cling",
  "clone": "clone",
  "clumsy": "clumsy",
  "club": "club",
  "coalition": "coalition",
  "coarse": "coarse",
  "clue": "clue",
  "cognitive": "cognitive",
  "clothe": "clothe",
  "clinic": "clinic",
  "coincide": "coincide",
  "coincidence": "coincidence",
  "collaborate": "collaborate",
  "collective": "collective",
  "collision": "collision",
  "colonial": "colonial",
  "colony": "colony",
  "commerce": "commerce",
  "commander": "commander",
  "comfort": "comfort",
  "command": "command",
  "combination": "combination",
  "comedy": "comedy",
  "commercial": "commercial",
  "commission": "commission",
  "commit": "commit",
  "commitment": "commitment",
  "committee": "committee",
  "commodity": "commodity",
  "communicate": "communicate",
  "communication": "communication",
  "community": "community",
  "communist": "communist",
  "companion": "companion",
  "complexity": "complexity",
  "compact": "compact",
  "competitor": "competitor",
  "complex": "complex",
  "competent": "competent",
  "comprehensive": "comprehensive",
  "concerned": "concerned",
  "compromise": "compromise",
  "comprise": "comprise",
  "competitive": "competitive",
  "concert": "concert",
  "conference": "conference",
  "confront": "confront",
  "consciousness": "consciousness",
  "confine": "confine",
  "conservative": "conservative",
  "consideration": "consideration",
  "constitute": "constitute",
  "constitution": "constitution",
  "consumer": "consumer",
  "continual": "continual",
  "consult": "consult",
  "continent": "continent",
  "consumption": "consumption",
  "continuous": "continuous",
  "constantly": "constantly",
  "contradiction": "contradiction",
  "contribution": "contribution",
  "controversial": "controversial",
  "convenience": "convenience",
  "convention": "convention",
  "conventional": "conventional",
  "convey": "convey",
  "conversion": "conversion",
  "cooperation": "cooperation",
  "cope": "cope",
  "correspond": "correspond",
  "cooperate": "cooperate",
  "correction": "correction",
  "correspondent": "correspondent",
  "corridor": "corridor",
  "corporation": "corporation",
  "corrupt": "corrupt",
  "corruption": "corruption",
  "cotton": "cotton",
  "cough": "cough",
  "could": "could",
  "council": "council",
  "counter": "counter",
  "courage": "courage",
  "county": "county",
  "crew": "crew",
  "countryside": "countryside",
  "creation": "creation",
  "coverage": "coverage",
  "crisis": "crisis",
  "creative": "creative",
  "counsel": "counsel",
  "criticism": "criticism",
  "critical": "critical",
  "crop": "crop",
  "cruel": "cruel",
  "crush": "crush",
  "curiosity": "curiosity",
  "crystal": "crystal",
  "currently": "currently",
  "curriculum": "curriculum",
  "customer": "customer",
  "cycle": "cycle",
  "then": "then",
  "eyes": "eyes",
  "even": "even",
  "more": "more",
  "been": "been",
  "there": "there",
  "says": "says",
  "right": "right",
  "them": "them",
  "would": "would",
  "should": "should",
  "didn": "didn",
  "myself": "myself",
  "things": "things",
  "okay": "okay",
  "doesn": "doesn",
  "were": "were",
  "hands": "hands",
  "email": "email",
  "looks": "looks",
  "best": "best",
  "words": "words",
  "shit": "shit",
  "lips": "lips",
  "years": "years",
  "someone": "someone",
  "thought": "thought",
  "person": "person",
  "thanks": "thanks",
  "pull": "pull",
  "screen": "screen",
  "nods": "nods",
  "pulls": "pulls",
  "comes": "comes",
  "turns": "turns",
  "takes": "takes",
  "friends": "friends",
  "though": "though",
  "yeah": "yeah",
  "said": "said",
  "these": "these",
  "makes": "makes",
  "message": "message",
  "emails": "emails",
  "expression": "expression",
  "fingers": "fingers",
  "wasn": "wasn",
  "shakes": "shakes",
  "feels": "feels",
  "many": "many",
  "made": "made",
  "grin": "grin",
  "shoulders": "shoulders",
  "does": "does",
  "knew": "knew",
  "sent": "sent",
  "half": "half",
  "real": "real",
  "times": "times",
  "parents": "parents",
  "probably": "probably",
  "shouldn": "shouldn",
  "those": "those",
  "skin": "skin",
  "exactly": "exactly",
  "seems": "seems",
  "sounds": "sounds",
  "closer": "closer",
  "told": "told",
  "smiles": "smiles",
  "leans": "leans",
  "cubicle": "cubicle",
  "stares": "stares",
  "pretty": "pretty",
  "folder": "folder",
  "drops": "drops",
  "done": "done",
  "goes": "goes",
  "somehow": "somehow",
  "quickly": "quickly",
  "days": "days",
  "weird": "weird",
  "seen": "seen",
  "gives": "gives",
  "appears": "appears",
  "minutes": "minutes",
  "fake": "fake",
  "starts": "starts",
  "calls": "calls",
  "boardroom": "boardroom",
  "laugh": "laugh",
  "arms": "arms",
  "hits": "hits",
  "terrible": "terrible",
  "true": "true",
  "shifts": "shifts",
  "outside": "outside",
  "hasn": "hasn",
  "walks": "walks",
  "fuck": "fuck",
  "able": "able",
  "several": "several",
  "suddenly": "suddenly",
  "feet": "feet",
  "employee": "employee",
  "reply": "reply",
  "went": "went",
  "chin": "chin",
  "herself": "herself",
  "holds": "holds",
  "bathroom": "bathroom",
  "continues": "continues",
  "monitor": "monitor",
  "ellie": "ellie",
  "haven": "haven",
  "blink": "blink",
  "himself": "himself",
  "gone": "gone",
  "knows": "knows",
  "means": "means",
  "grabs": "grabs",
  "cheeks": "cheeks",
  "tiny": "tiny",
  "deep": "deep",
  "twists": "twists",
  "tilts": "tilts",
  "aunty": "aunty",
  "flashes": "flashes",
  "year": "year",
  "hours": "hours",
  "text": "text",
  "chuckle": "chuckle",
  "wouldn": "wouldn",
  "weeks": "weeks",
  "gets": "gets",
  "took": "took",
  "aren": "aren",
  "needs": "needs",
  "couldn": "couldn",
  "persian": "persian",
  "stops": "stops",
  "donut": "donut",
  "carl": "carl",
  "colleagues": "colleagues",
  "found": "found",
  "meant": "meant",
  "worst": "worst",
  "relief": "relief",
  "speak": "speak",
  "came": "came",
  "bags": "bags",
  "sort": "sort",
  "search": "search",
  "mouse": "mouse",
  "slowly": "slowly",
  "spent": "spent",
  "silent": "silent",
  "attention": "attention",
  "inbox": "inbox",
  "grins": "grins",
  "five": "five",
  "keeps": "keeps",
  "important": "important",
  "employees": "employees",
  "whispers": "whispers",
  "sits": "sits",
  "asks": "asks",
  "obviously": "obviously",
  "lights": "lights",
  "shut": "shut",
  "tightens": "tightens",
  "questions": "questions",
  "reads": "reads",
  "clicks": "clicks",
  "brow": "brow",
  "thoughts": "thoughts",
  "tears": "tears",
  "pushes": "pushes",
  "miss": "miss",
  "begins": "begins",
  "known": "known",
  "grandma": "grandma",
  "raises": "raises",
  "hoodie": "hoodie",
  "lets": "lets",
  "heard": "heard",
  "wants": "wants",
  "happens": "happens",
  "catches": "catches",
  "soft": "soft",
  "bullshit": "bullshit",
  "felt": "felt",
  "morale": "morale",
  "printer": "printer",
  "goodwin": "goodwin",
  "normally": "normally",
  "taken": "taken",
  "claps": "claps",
  "sometimes": "sometimes",
  "lately": "lately",
  "ready": "ready",
  "grid": "grid",
  "practically": "practically",
  "promotion": "promotion",
  "pops": "pops",
  "temples": "temples",
  "honestly": "honestly",
  "mostly": "mostly",
  "lower": "lower",
  "randal": "randal",
  "breaks": "breaks",
  "mutter": "mutter",
  "immediately": "immediately",
  "pauses": "pauses",
  "returns": "returns",
  "marches": "marches",
  "presses": "presses",
  "heads": "heads",
  "draws": "draws",
  "pants": "pants",
  "christmas": "christmas",
  "longer": "longer",
  "possible": "possible",
  "proud": "proud",
  "town": "town",
  "hollow": "hollow",
  "messages": "messages",
  "insides": "insides",
  "taps": "taps",
  "greg": "greg",
  "cake": "cake",
  "speaks": "speaks",
  "anna": "anna",
  "joffrey": "joffrey",
  "fists": "fists",
  "corners": "corners",
  "papers": "papers",
  "somewhere": "somewhere",
  "falls": "falls",
  "warmth": "warmth",
  "brows": "brows",
  "marla": "marla",
  "widen": "widen",
  "palms": "palms",
  "instantly": "instantly",
  "stands": "stands",
  "smith": "smith",
  "pointedly": "pointedly",
  "keyboard": "keyboard",
  "pods": "pods",
  "fact": "fact",
  "smirk": "smirk",
  "warhammer": "warhammer",
  "seconds": "seconds",
  "twice": "twice",
  "cube": "cube",
  "blurt": "blurt",
  "lives": "lives",
  "moms": "moms",
  "joey": "joey",
  "eyebrows": "eyebrows",
  "caught": "caught",
  "given": "given",
  "faces": "faces",
  "special": "special",
  "throws": "throws",
  "easier": "easier",
  "mutters": "mutters",
  "zebra": "zebra",
  "steps": "steps",
  "booth": "booth",
  "ways": "ways",
  "harpercollins": "harpercollins",
  "dart": "dart",
  "chairs": "chairs",
  "literally": "literally",
  "headphones": "headphones",
  "desks": "desks",
  "months": "months",
  "others": "others",
  "twitch": "twitch",
  "kids": "kids",
  "huffs": "huffs",
  "softens": "softens",
  "gotten": "gotten",
  "weren": "weren",
  "thinks": "thinks",
  "lowers": "lowers",
  "threshold": "threshold",
  "horrible": "horrible",
  "bite": "bite",
  "laughs": "laughs",
  "console": "console",
  "carpool": "carpool",
  "puts": "puts",
  "tables": "tables",
  "laughter": "laughter",
  "lies": "lies",
  "sends": "sends",
  "guys": "guys",
  "places": "places",
  "brought": "brought",
  "rolls": "rolls",
  "dread": "dread",
  "rubs": "rubs",
  "halts": "halts",
  "tracks": "tracks",
  "plans": "plans",
  "sighs": "sighs",
  "croak": "croak",
  "meetings": "meetings",
  "issues": "issues",
  "teeth": "teeth",
  "elevator": "elevator",
  "lunchroom": "lunchroom",
  "seriously": "seriously",
  "tense": "tense",
  "escapes": "escapes",
  "huff": "huff",
  "ideas": "ideas",
  "boxes": "boxes",
  "perfectly": "perfectly",
  "eyebrow": "eyebrow",
  "favorite": "favorite",
  "names": "names",
  "written": "written",
  "none": "none",
  "pieces": "pieces",
  "executive": "executive",
  "blinks": "blinks",
  "messy": "messy",
  "tugs": "tugs",
  "opens": "opens",
  "passenger": "passenger",
  "bakery": "bakery",
  "ashe": "ashe",
  "boosters": "boosters",
  "admin": "admin",
  "specific": "specific",
  "documents": "documents",
  "fridge": "fridge",
  "casual": "casual",
  "layoffs": "layoffs",
  "slides": "slides",
  "winces": "winces",
  "reports": "reports",
  "slightly": "slightly",
  "seats": "seats",
  "bottles": "bottles",
  "four": "four",
  "unfortunately": "unfortunately",
  "leaves": "leaves",
  "deeper": "deeper",
  "farsi": "farsi",
  "passes": "passes",
  "pounds": "pounds",
  "crochet": "crochet",
  "broke": "broke",
  "earlier": "earlier",
  "chuckles": "chuckles",
  "shrugs": "shrugs",
  "definitely": "definitely",
  "broken": "broken",
  "fifteen": "fifteen",
  "inventory": "inventory",
  "cuts": "cuts",
  "celeste": "celeste",
  "donuts": "donuts",
  "dogs": "dogs",
  "engagement": "engagement",
  "flips": "flips",
  "shows": "shows",
  "walls": "walls",
  "garbage": "garbage",
  "notices": "notices",
  "pins": "pins",
  "runs": "runs",
  "usually": "usually",
  "jolt": "jolt",
  "million": "million",
  "account": "account",
  "nails": "nails",
  "heartbeat": "heartbeat",
  "notepad": "notepad",
  "jumps": "jumps",
  "aunties": "aunties",
  "ticks": "ticks",
  "pipes": "pipes",
  "drifts": "drifts",
  "nudges": "nudges",
  "cards": "cards",
  "makeup": "makeup",
  "instagram": "instagram",
  "glasses": "glasses",
  "themselves": "themselves",
  "jobs": "jobs",
  "quietly": "quietly",
  "families": "families",
  "grew": "grew",
  "angst": "angst",
  "legs": "legs",
  "accept": "accept",
  "forgot": "forgot",
  "wrinkles": "wrinkles",
  "clears": "clears",
  "online": "online",
  "rushes": "rushes",
  "absolutely": "absolutely",
  "promise": "promise",
  "mandatory": "mandatory",
  "habib": "habib",
  "silently": "silently",
  "cackle": "cackle",
  "drinks": "drinks",
  "data": "data",
  "lifts": "lifts",
  "folders": "folders",
  "knuckles": "knuckles",
  "locks": "locks",
  "miserable": "miserable",
  "crap": "crap",
  "tells": "tells",
  "doors": "doors",
  "staples": "staples",
  "despite": "despite",
  "gestures": "gestures",
  "knees": "knees",
  "bounce": "bounce",
  "bones": "bones",
  "ones": "ones",
  "lungs": "lungs",
  "hers": "hers",
  "fluorescent": "fluorescent",
  "technically": "technically",
  "gave": "gave",
  "unfortunate": "unfortunate",
  "sets": "sets",
  "discount": "discount",
  "realization": "realization",
  "ends": "ends",
  "closes": "closes",
  "glances": "glances",
  "pats": "pats",
  "roya": "roya",
  "twitches": "twitches",
  "physically": "physically",
  "rings": "rings",
  "professional": "professional",
  "footsteps": "footsteps",
  "picks": "picks",
  "forms": "forms",
  "flinch": "flinch",
  "spots": "spots",
  "points": "points",
  "curls": "curls",
  "lingers": "lingers",
  "shoes": "shoes",
  "types": "types",
  "lobby": "lobby",
  "vibes": "vibes",
  "crouch": "crouch",
  "courses": "courses",
  "scroll": "scroll",
  "letters": "letters",
  "display": "display",
  "icon": "icon",
  "became": "became",
  "kept": "kept",
  "awkward": "awkward",
  "switch": "switch",
  "crawls": "crawls",
  "dollars": "dollars",
  "moves": "moves",
  "sees": "sees",
  "uncomfortable": "uncomfortable",
  "miriam": "miriam",
  "ears": "ears",
  "expressions": "expressions",
  "reaches": "reaches",
  "vibe": "vibe",
  "sharply": "sharply",
  "creepy": "creepy",
  "roles": "roles",
  "lane": "lane",
  "holy": "holy",
  "maroon": "maroon",
  "moments": "moments",
  "texts": "texts",
  "reshteh": "reshteh"
};

// 5. 拼写自动校正与形近词表
const corrections = {
  "seperate": "separate",
  "definately": "definitely",
  "recieve": "receive",
  "accomodate": "accommodate",
  "occured": "occurred",
  "untill": "until",
  "goverment": "government",
  "truely": "truly"
};
